# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.analytics_query_response import AnalyticsQueryResponse
from ..types.analytics_schema_response import AnalyticsSchemaResponse
from ..types.signals_metadata_response import SignalsMetadataResponse
from .raw_client import AsyncRawAnalyticsExperimentalClient, RawAnalyticsExperimentalClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class AnalyticsExperimentalClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawAnalyticsExperimentalClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawAnalyticsExperimentalClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawAnalyticsExperimentalClient
        """
        return self._raw_client

    def execute_analytics_query(
        self, *, query: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AnalyticsQueryResponse:
        """
        ⚠️ **Experimental** — this endpoint may change or be removed without notice and is not subject to v2 backwards-compatibility guarantees. Do not build production-critical integrations against it yet.

        Runs a single ClickHouse SELECT (or WITH … SELECT) against your organization's analytics views. Before writing a query, call `getAnalyticsSchema` (GET /schema) for the available views and columns, and `getSignalsMetadata` (GET /signals/metadata) for the JSON paths inside `fact_signal.data`. Results are automatically scoped to your organization — no org filter is needed or possible. Only SELECT/WITH statements are accepted.

        Conventions: monetary amounts are minor units (cents — divide by 100 for the major unit); most are integers, but `fact_cost.cost_amount` is fractional cents (Decimal) since a single AI call usually costs less than a cent; 64-bit integers (counts, ids, amounts) are returned as JSON strings to preserve precision, so parse them client-side. Query signal payloads via JSON paths, e.g. `SELECT data.country::String AS country, count() FROM fact_signal GROUP BY country`.

        Limits: 30 seconds of execution time and 10,000 result rows (truncation is flagged via `meta.truncated`). Prefer aggregates and a `created_at` date filter on large tables — this endpoint is for interactive analytics, not bulk export.

        Parameters
        ----------
        query : str
            A single ClickHouse SELECT (or WITH ... SELECT) statement against the analytics views. Results are automatically scoped to your organization. See GET /schema for the available views and columns.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AnalyticsQueryResponse
            200

        Examples
        --------
        from paid import Paid

        client = Paid(
            token="YOUR_TOKEN",
        )
        client.analytics_experimental.execute_analytics_query(
            query="SELECT signal_name, count() AS signals FROM fact_signal WHERE created_at > now() - INTERVAL 30 DAY GROUP BY signal_name ORDER BY signals DESC",
        )
        """
        _response = self._raw_client.execute_analytics_query(query=query, request_options=request_options)
        return _response.data

    def get_analytics_schema(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AnalyticsSchemaResponse:
        """
        ⚠️ **Experimental** — this endpoint may change or be removed without notice and is not subject to v2 backwards-compatibility guarantees. Do not build production-critical integrations against it yet.

        Returns the analytics views available to POST /query, with column names, ClickHouse types, and descriptions. Dimensions (`dim_*`) describe entities; facts (`fact_*`) are event/transaction tables that join to dimensions via the `*_id` columns described in each comment.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AnalyticsSchemaResponse
            200

        Examples
        --------
        from paid import Paid

        client = Paid(
            token="YOUR_TOKEN",
        )
        client.analytics_experimental.get_analytics_schema()
        """
        _response = self._raw_client.get_analytics_schema(request_options=request_options)
        return _response.data

    def get_signals_metadata(
        self,
        *,
        signal_name: typing.Optional[str] = None,
        from_date: typing.Optional[dt.datetime] = None,
        to_date: typing.Optional[dt.datetime] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SignalsMetadataResponse:
        """
        ⚠️ **Experimental** — this endpoint may change or be removed without notice and is not subject to v2 backwards-compatibility guarantees. Do not build production-critical integrations against it yet.

        Lists the JSON paths (and their observed types) present in the `data` payload of your signals within a time window (default: last 30 days), grouped by signal name. Use the returned paths in queries against `fact_signal`, e.g. `WHERE data.<path>::String = '...'`.

        Parameters
        ----------
        signal_name : typing.Optional[str]
            Restrict discovery to a single signal name.

        from_date : typing.Optional[dt.datetime]
            Start of the discovery window. Defaults to 30 days ago.

        to_date : typing.Optional[dt.datetime]
            End of the discovery window. Defaults to now.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SignalsMetadataResponse
            200

        Examples
        --------
        from paid import Paid

        client = Paid(
            token="YOUR_TOKEN",
        )
        client.analytics_experimental.get_signals_metadata()
        """
        _response = self._raw_client.get_signals_metadata(
            signal_name=signal_name, from_date=from_date, to_date=to_date, request_options=request_options
        )
        return _response.data


class AsyncAnalyticsExperimentalClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawAnalyticsExperimentalClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawAnalyticsExperimentalClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawAnalyticsExperimentalClient
        """
        return self._raw_client

    async def execute_analytics_query(
        self, *, query: str, request_options: typing.Optional[RequestOptions] = None
    ) -> AnalyticsQueryResponse:
        """
        ⚠️ **Experimental** — this endpoint may change or be removed without notice and is not subject to v2 backwards-compatibility guarantees. Do not build production-critical integrations against it yet.

        Runs a single ClickHouse SELECT (or WITH … SELECT) against your organization's analytics views. Before writing a query, call `getAnalyticsSchema` (GET /schema) for the available views and columns, and `getSignalsMetadata` (GET /signals/metadata) for the JSON paths inside `fact_signal.data`. Results are automatically scoped to your organization — no org filter is needed or possible. Only SELECT/WITH statements are accepted.

        Conventions: monetary amounts are minor units (cents — divide by 100 for the major unit); most are integers, but `fact_cost.cost_amount` is fractional cents (Decimal) since a single AI call usually costs less than a cent; 64-bit integers (counts, ids, amounts) are returned as JSON strings to preserve precision, so parse them client-side. Query signal payloads via JSON paths, e.g. `SELECT data.country::String AS country, count() FROM fact_signal GROUP BY country`.

        Limits: 30 seconds of execution time and 10,000 result rows (truncation is flagged via `meta.truncated`). Prefer aggregates and a `created_at` date filter on large tables — this endpoint is for interactive analytics, not bulk export.

        Parameters
        ----------
        query : str
            A single ClickHouse SELECT (or WITH ... SELECT) statement against the analytics views. Results are automatically scoped to your organization. See GET /schema for the available views and columns.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AnalyticsQueryResponse
            200

        Examples
        --------
        import asyncio

        from paid import AsyncPaid

        client = AsyncPaid(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.analytics_experimental.execute_analytics_query(
                query="SELECT signal_name, count() AS signals FROM fact_signal WHERE created_at > now() - INTERVAL 30 DAY GROUP BY signal_name ORDER BY signals DESC",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.execute_analytics_query(query=query, request_options=request_options)
        return _response.data

    async def get_analytics_schema(
        self, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AnalyticsSchemaResponse:
        """
        ⚠️ **Experimental** — this endpoint may change or be removed without notice and is not subject to v2 backwards-compatibility guarantees. Do not build production-critical integrations against it yet.

        Returns the analytics views available to POST /query, with column names, ClickHouse types, and descriptions. Dimensions (`dim_*`) describe entities; facts (`fact_*`) are event/transaction tables that join to dimensions via the `*_id` columns described in each comment.

        Parameters
        ----------
        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AnalyticsSchemaResponse
            200

        Examples
        --------
        import asyncio

        from paid import AsyncPaid

        client = AsyncPaid(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.analytics_experimental.get_analytics_schema()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_analytics_schema(request_options=request_options)
        return _response.data

    async def get_signals_metadata(
        self,
        *,
        signal_name: typing.Optional[str] = None,
        from_date: typing.Optional[dt.datetime] = None,
        to_date: typing.Optional[dt.datetime] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> SignalsMetadataResponse:
        """
        ⚠️ **Experimental** — this endpoint may change or be removed without notice and is not subject to v2 backwards-compatibility guarantees. Do not build production-critical integrations against it yet.

        Lists the JSON paths (and their observed types) present in the `data` payload of your signals within a time window (default: last 30 days), grouped by signal name. Use the returned paths in queries against `fact_signal`, e.g. `WHERE data.<path>::String = '...'`.

        Parameters
        ----------
        signal_name : typing.Optional[str]
            Restrict discovery to a single signal name.

        from_date : typing.Optional[dt.datetime]
            Start of the discovery window. Defaults to 30 days ago.

        to_date : typing.Optional[dt.datetime]
            End of the discovery window. Defaults to now.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        SignalsMetadataResponse
            200

        Examples
        --------
        import asyncio

        from paid import AsyncPaid

        client = AsyncPaid(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.analytics_experimental.get_signals_metadata()


        asyncio.run(main())
        """
        _response = await self._raw_client.get_signals_metadata(
            signal_name=signal_name, from_date=from_date, to_date=to_date, request_options=request_options
        )
        return _response.data
