# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .amendment_billing_type import AmendmentBillingType
from .amendment_charge_type import AmendmentChargeType
from .amendment_pricing_model import AmendmentPricingModel


class AmendmentPricingClause(UniversalBaseModel):
    """
    One applicability clause. Match every non-empty list. Empty lists constrain nothing.
    """

    charge_types: typing_extensions.Annotated[
        typing.Optional[typing.List[AmendmentChargeType]],
        FieldMetadata(alias="chargeTypes"),
        pydantic.Field(alias="chargeTypes", description="Charge types this clause matches. Empty matches any."),
    ] = None
    billing_types: typing_extensions.Annotated[
        typing.Optional[typing.List[AmendmentBillingType]],
        FieldMetadata(alias="billingTypes"),
        pydantic.Field(alias="billingTypes", description="Billing types this clause matches. Empty matches any."),
    ] = None
    pricing_models: typing_extensions.Annotated[
        typing.Optional[typing.List[AmendmentPricingModel]],
        FieldMetadata(alias="pricingModels"),
        pydantic.Field(alias="pricingModels", description="Pricing models this clause matches. Empty matches any."),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
