# This file was auto-generated by Fern from our API Definition.

import typing

AmendmentPricingModel = typing.Union[
    typing.Literal[
        "PerUnit",
        "VolumePricing",
        "GraduatedPricing",
        "PrepaidCredits",
        "BracketedPrepaidCredits",
        "PercentOfTotal",
        "CostPlus",
    ],
    typing.Any,
]
