# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .amendment_axis_choice_value import AmendmentAxisChoiceValue
from .amendment_axis_id import AmendmentAxisId
from .amendment_treatment_source import AmendmentTreatmentSource


class AmendmentPlanTreatmentResolution(UniversalBaseModel):
    intent_index: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="intentIndex"),
        pydantic.Field(alias="intentIndex", description="Index of the request intent that produced this entry."),
    ]
    axis: AmendmentAxisId
    value: AmendmentAxisChoiceValue
    source: AmendmentTreatmentSource
    reason: str = pydantic.Field()
    """
    Human-readable explanation of why this value was chosen.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
