# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CheckoutPlanInput(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Plan identifier, as returned by the list plans endpoint. Selects a specific plan within the product.
    """

    features: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Override the feature bullet points shown for this plan on the hosted checkout page.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
