# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .checkout_product import CheckoutProduct
from .checkout_status import CheckoutStatus


class Checkout(UniversalBaseModel):
    id: str
    url: str
    status: CheckoutStatus
    products: typing.List[CheckoutProduct]
    customer_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="customerId"), pydantic.Field(alias="customerId")
    ] = None
    success_url: typing_extensions.Annotated[str, FieldMetadata(alias="successUrl"), pydantic.Field(alias="successUrl")]
    cancel_url: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="cancelUrl"), pydantic.Field(alias="cancelUrl")
    ] = None
    expires_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="expiresAt"), pydantic.Field(alias="expiresAt")
    ] = None
    metadata: typing.Optional[typing.Dict[str, typing.Any]] = None
    created_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")
    ]
    updated_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="updatedAt"), pydantic.Field(alias="updatedAt")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
