# This file was auto-generated by Fern from our API Definition.

import typing

CreateOrderLineAttributeRequestPricingBillingFrequency = typing.Union[
    typing.Literal["monthly", "quarterly", "semiAnnually", "annual", "custom"], typing.Any
]
