# This file was auto-generated by Fern from our API Definition.

import typing

CreateOrderLineAttributeRequestPricingCreditBenefitsItemRolloverDurationUnit = typing.Union[
    typing.Literal["days", "months"], typing.Any
]
