# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .create_order_line_attribute_request_pricing_price_points_tiers_item import (
    CreateOrderLineAttributeRequestPricingPricePointsTiersItem,
)


class CreateOrderLineAttributeRequestPricingPricePoints(UniversalBaseModel):
    currency: typing.Optional[str] = None
    unit_price: typing_extensions.Annotated[float, FieldMetadata(alias="unitPrice"), pydantic.Field(alias="unitPrice")]
    min_quantity: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="minQuantity"), pydantic.Field(alias="minQuantity")
    ] = None
    included_quantity: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="includedQuantity"), pydantic.Field(alias="includedQuantity")
    ] = None
    tiers: typing.Optional[typing.List[CreateOrderLineAttributeRequestPricingPricePointsTiersItem]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
