# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .create_order_line_attribute_request_pricing_billing_frequency import (
    CreateOrderLineAttributeRequestPricingBillingFrequency,
)
from .create_order_line_attribute_request_pricing_billing_type import CreateOrderLineAttributeRequestPricingBillingType
from .create_order_line_attribute_request_pricing_charge_type import CreateOrderLineAttributeRequestPricingChargeType
from .create_order_line_attribute_request_pricing_credit_benefits_item import (
    CreateOrderLineAttributeRequestPricingCreditBenefitsItem,
)
from .create_order_line_attribute_request_pricing_price_points import CreateOrderLineAttributeRequestPricingPricePoints
from .create_order_line_attribute_request_pricing_pricing_model import (
    CreateOrderLineAttributeRequestPricingPricingModel,
)
from .create_order_line_attribute_request_pricing_signal_type import CreateOrderLineAttributeRequestPricingSignalType


class CreateOrderLineAttributeRequestPricing(UniversalBaseModel):
    event_name: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="eventName"), pydantic.Field(alias="eventName")
    ] = None
    charge_type: typing_extensions.Annotated[
        CreateOrderLineAttributeRequestPricingChargeType,
        FieldMetadata(alias="chargeType"),
        pydantic.Field(alias="chargeType"),
    ]
    price_points: typing_extensions.Annotated[
        CreateOrderLineAttributeRequestPricingPricePoints,
        FieldMetadata(alias="pricePoints"),
        pydantic.Field(alias="pricePoints"),
    ]
    pricing_model: typing_extensions.Annotated[
        typing.Optional[CreateOrderLineAttributeRequestPricingPricingModel],
        FieldMetadata(alias="pricingModel"),
        pydantic.Field(alias="pricingModel"),
    ] = None
    billing_frequency: typing_extensions.Annotated[
        typing.Optional[CreateOrderLineAttributeRequestPricingBillingFrequency],
        FieldMetadata(alias="billingFrequency"),
        pydantic.Field(alias="billingFrequency"),
    ] = None
    billing_frequency_custom_months: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="billingFrequencyCustomMonths"),
        pydantic.Field(alias="billingFrequencyCustomMonths"),
    ] = None
    billing_type: typing_extensions.Annotated[
        typing.Optional[CreateOrderLineAttributeRequestPricingBillingType],
        FieldMetadata(alias="billingType"),
        pydantic.Field(alias="billingType"),
    ] = None
    signal_type: typing_extensions.Annotated[
        typing.Optional[CreateOrderLineAttributeRequestPricingSignalType],
        FieldMetadata(alias="signalType"),
        pydantic.Field(alias="signalType"),
    ] = None
    credits_currency_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="creditsCurrencyId"), pydantic.Field(alias="creditsCurrencyId")
    ] = None
    credit_cost: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="creditCost"), pydantic.Field(alias="creditCost")
    ] = None
    overage_unit_price: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="overageUnitPrice"), pydantic.Field(alias="overageUnitPrice")
    ] = None
    credit_benefits: typing_extensions.Annotated[
        typing.Optional[typing.List[CreateOrderLineAttributeRequestPricingCreditBenefitsItem]],
        FieldMetadata(alias="creditBenefits"),
        pydantic.Field(alias="creditBenefits"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
