# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .amendment_axis_relevance import AmendmentAxisRelevance
from .credit_grant_axis_options_options_item import CreditGrantAxisOptionsOptionsItem


class CreditGrantAxisOptions(UniversalBaseModel):
    relevance: AmendmentAxisRelevance
    options: typing.List[CreditGrantAxisOptionsOptionsItem]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
