# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .credit_transaction_currency import CreditTransactionCurrency
from .credit_transaction_customer import CreditTransactionCustomer
from .credit_transaction_product import CreditTransactionProduct
from .credit_transaction_type import CreditTransactionType


class CreditTransaction(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Unique identifier for this credit transaction.
    """

    customer: CreditTransactionCustomer
    credit_currency: typing_extensions.Annotated[
        CreditTransactionCurrency, FieldMetadata(alias="creditCurrency"), pydantic.Field(alias="creditCurrency")
    ]
    type: CreditTransactionType = pydantic.Field()
    """
    Transaction type: `grant` adds credits, `spend` consumes them (negative amount), `pendingGrant` records credits awaiting payment.
    """

    amount: str = pydantic.Field()
    """
    Exact signed transaction amount in credits, as a decimal string: positive for grants, negative for spends. Exact at any magnitude, and at the full 6 decimal places.
    """

    origin_code: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="originCode"),
        pydantic.Field(
            alias="originCode",
            description="Origin of the credit pool this transaction touched (e.g. `purchased`, or a custom label). `unknown` when the transaction is not linked to a pool with an origin.",
        ),
    ]
    event_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="eventName"),
        pydantic.Field(
            alias="eventName",
            description="Usage event that produced this spend. Null for grants and non-signal spends.",
        ),
    ] = None
    signal_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="signalId"),
        pydantic.Field(
            alias="signalId",
            description="ID of the usage signal that produced this spend, resolvable via `GET /api/v2/signals/{id}` (including the signal's data payload). Null for grants and non-signal spends.",
        ),
    ] = None
    order_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="orderId"),
        pydantic.Field(alias="orderId", description="Paid order display ID this transaction is linked to, if any."),
    ] = None
    product: typing.Optional[CreditTransactionProduct] = None
    created_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="createdAt"),
        pydantic.Field(
            alias="createdAt",
            description="When the originating signal was recorded, or when the transaction was recorded if it has no signal.",
        ),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
