# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class CreditGrantCreateRequest(UniversalBaseModel):
    credit_currency_key: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="creditCurrencyKey"),
        pydantic.Field(
            alias="creditCurrencyKey",
            description="Stable machine-readable key for the active credit currency to grant.",
        ),
    ]
    amount: int = pydantic.Field()
    """
    Number of credits to grant. This is not a monetary amount.
    """

    starts_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="startsAt"),
        pydantic.Field(
            alias="startsAt",
            description="When these credits become spendable, as an RFC3339 datetime with timezone. Must be at or before the current server time. Defaults to the current server time when omitted.",
        ),
    ] = None
    expires_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="expiresAt"),
        pydantic.Field(
            alias="expiresAt",
            description="When these credits expire, as an RFC3339 datetime with timezone. Omit or set null for credits that do not expire.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
