# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class CreditGrant(UniversalBaseModel):
    available: float
    used: float
    total: float
    rollover_amount: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="rolloverAmount"), pydantic.Field(alias="rolloverAmount")
    ] = None
    period_start: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="periodStart"), pydantic.Field(alias="periodStart")
    ]
    period_end: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="periodEnd"), pydantic.Field(alias="periodEnd")
    ] = None
    rollover_end_date: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="rolloverEndDate"), pydantic.Field(alias="rolloverEndDate")
    ] = None
    expires_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="expiresAt"), pydantic.Field(alias="expiresAt")
    ] = None
    is_in_rollover_window: typing_extensions.Annotated[
        bool, FieldMetadata(alias="isInRolloverWindow"), pydantic.Field(alias="isInRolloverWindow")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
