# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .customer_unit import CustomerUnit
from .pagination import Pagination


class CustomerUnitListResponse(UniversalBaseModel):
    data: typing.List[CustomerUnit] = pydantic.Field()
    """
    Flat list ordered by creation time; assemble the tree client-side from `parentExternalId` (`null` on the root).
    """

    pagination: Pagination

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
