# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .currency_code import CurrencyCode
from .customer_state_checkout_link import CustomerStateCheckoutLink
from .customer_state_credit_summary import CustomerStateCreditSummary
from .customer_state_customer import CustomerStateCustomer
from .customer_state_order import CustomerStateOrder
from .customer_state_seats import CustomerStateSeats


class CustomerState(UniversalBaseModel):
    customer: CustomerStateCustomer
    default_currency: typing_extensions.Annotated[
        CurrencyCode, FieldMetadata(alias="defaultCurrency"), pydantic.Field(alias="defaultCurrency")
    ]
    orders: typing.List[CustomerStateOrder]
    seats: CustomerStateSeats
    checkout_links: typing_extensions.Annotated[
        typing.List[CustomerStateCheckoutLink],
        FieldMetadata(alias="checkoutLinks"),
        pydantic.Field(alias="checkoutLinks"),
    ]
    credits: CustomerStateCreditSummary
    timestamp: dt.datetime

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
