# This file was auto-generated by Fern from our API Definition.

import typing

CustomViewPreviewHarnessRequestSyntheticValueItemType = typing.Union[
    typing.Literal["date", "number", "string", "boolean"], typing.Any
]
