# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .customer_unit_cap_set_frequency import CustomerUnitCapSetFrequency


class CustomerUnitCapSet(UniversalBaseModel):
    amount: float = pydantic.Field()
    """
    The cap, in credits of the currency, per period. Must be positive.
    """

    frequency: typing.Optional[CustomerUnitCapSetFrequency] = pydantic.Field(default=None)
    """
    Period length. Periods start on the day-of-month of `effectiveFrom` (UTC), clamped in shorter months.
    """

    credits_currency_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="creditsCurrencyId"),
        pydantic.Field(
            alias="creditsCurrencyId",
            description="The credits currency to cap. Omit it only when the organization has exactly one credits currency, which is then used; otherwise it is required.",
        ),
    ] = None
    effective_from: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="effectiveFrom"),
        pydantic.Field(
            alias="effectiveFrom",
            description="ISO 8601 timestamp. When the cap starts applying and the anchor day for its periods (UTC). Defaults to now when omitted. Spend earlier in the period that contains it still counts toward the cap.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
