# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .custom_view_detail_period import CustomViewDetailPeriod
from .custom_view_detail_status import CustomViewDetailStatus


class CustomViewDetail(UniversalBaseModel):
    display_id: typing_extensions.Annotated[str, FieldMetadata(alias="displayId"), pydantic.Field(alias="displayId")]
    name: str
    description: typing.Optional[str] = None
    status: CustomViewDetailStatus
    query_ids: typing_extensions.Annotated[
        typing.List[str],
        FieldMetadata(alias="queryIds"),
        pydantic.Field(alias="queryIds", description="Ids of the result sets the render bundle will receive."),
    ]
    render_bundle: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="renderBundle"),
        pydantic.Field(
            alias="renderBundle",
            description="Self-contained HTML document rendered inside the isolated sandbox iframe.",
        ),
    ]
    period: typing.Optional[CustomViewDetailPeriod] = pydantic.Field(default=None)
    """
    The view's current default date range, or null if it uses no adjustable period.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
