# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CustomerUnitCapPeriod(UniversalBaseModel):
    start: dt.datetime = pydantic.Field()
    """
    Inclusive start of the period, UTC.
    """

    end: dt.datetime = pydantic.Field()
    """
    Exclusive end of the period, UTC.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
