# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .customer_unit_status import CustomerUnitStatus


class CustomerUnit(UniversalBaseModel):
    external_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="externalId"),
        pydantic.Field(
            alias="externalId",
            description="Your own id for the unit, unique within the customer; the identifier every unit route takes.",
        ),
    ]
    name: str = pydantic.Field()
    """
    Display name. Never used to address the unit.
    """

    external_type: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="externalType"),
        pydantic.Field(alias="externalType", description="Your structural vocabulary for the unit."),
    ] = None
    status: CustomerUnitStatus = pydantic.Field()
    """
    ACTIVE, or DELETED after a soft delete (one-way).
    """

    parent_external_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="parentExternalId"),
        pydantic.Field(
            alias="parentExternalId",
            description="`externalId` of the parent unit; `null` only on the customer's root unit.",
        ),
    ] = None
    is_root: typing_extensions.Annotated[
        bool,
        FieldMetadata(alias="isRoot"),
        pydantic.Field(
            alias="isRoot",
            description="Whether this unit is the customer's root: the one unit without a parent. Derived from the missing parent, not stored. At most one active root per customer; the root cannot be moved, and once deleted a new root can be created.",
        ),
    ]
    metadata: typing.Optional[typing.Dict[str, typing.Any]] = None
    created_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")
    ]
    updated_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="updatedAt"), pydantic.Field(alias="updatedAt")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
