# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .end_attribute_intent_treatment import EndAttributeIntentTreatment


class EndAttributeIntent(UniversalBaseModel):
    order_line_attribute_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="orderLineAttributeId"),
        pydantic.Field(
            alias="orderLineAttributeId",
            description="Attribute UUID from the options response. Not the order display id.",
        ),
    ]
    treatment: typing.Optional[EndAttributeIntentTreatment] = pydantic.Field(default=None)
    """
    Recurring charges pick next-cycle vs settle-now. Usage price changes pick new usage only vs the whole current period.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
