# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .credit_grant_currency import CreditGrantCurrency
from .credit_grant_customer import CreditGrantCustomer
from .credit_grant_result import CreditGrantResult


class GrantCustomerCreditsResponse(UniversalBaseModel):
    created: bool = pydantic.Field()
    """
    True when this request created a new grant.
    """

    customer: CreditGrantCustomer
    credit_currency: typing_extensions.Annotated[
        CreditGrantCurrency, FieldMetadata(alias="creditCurrency"), pydantic.Field(alias="creditCurrency")
    ]
    grant: CreditGrantResult
    created_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
