# This file was auto-generated by Fern from our API Definition.

import typing

InvoiceStatus = typing.Union[
    typing.Literal["building", "draft", "pending", "posted", "voided", "canceled", "error"], typing.Any
]
