# This file was auto-generated by Fern from our API Definition.

import typing

OneTimePerUnitInputFeeType = typing.Union[
    typing.Literal["setup", "onboarding", "implementation", "migration", "custom"], typing.Any
]
