# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class PaymentAllocation(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    Unique payment allocation identifier.
    """

    payment_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="paymentId"),
        pydantic.Field(alias="paymentId", description="The payment the amount was allocated from."),
    ]
    invoice_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="invoiceId"),
        pydantic.Field(alias="invoiceId", description="The invoice the allocated line belongs to."),
    ]
    invoice_line_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="invoiceLineId"),
        pydantic.Field(
            alias="invoiceLineId",
            description="The invoice line the amount was allocated to, as returned by the invoice lines endpoint.",
        ),
    ]
    amount: int = pydantic.Field()
    """
    Allocated amount in cents (minor currency units).
    """

    currency: str = pydantic.Field()
    """
    Three-letter ISO currency code.
    """

    type: str = pydantic.Field()
    """
    Allocation type: allocated or unallocated.
    """

    status: str = pydantic.Field()
    """
    Allocation status: posted, applied, or cancelled.
    """

    allocation_date: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="allocationDate"),
        pydantic.Field(alias="allocationDate", description="When the allocation was made."),
    ]
    created_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
