# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .payment_method_setup_setup_intent import PaymentMethodSetupSetupIntent


class PaymentMethodSetup(UniversalBaseModel):
    setup_intent: typing_extensions.Annotated[
        PaymentMethodSetupSetupIntent,
        FieldMetadata(alias="setupIntent"),
        pydantic.Field(alias="setupIntent", description="The setup intent created with the payment processor."),
    ]
    external_payment_method_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="externalPaymentMethodId"),
        pydantic.Field(
            alias="externalPaymentMethodId",
            description="The payment processor's identifier for the attached payment method, when already available.",
        ),
    ] = None
    customer_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="customerId"),
        pydantic.Field(alias="customerId", description="The customer the payment method is being attached to."),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
