# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .planned_add import PlannedAdd
from .planned_copy import PlannedCopy
from .planned_end import PlannedEnd
from .planned_order_term import PlannedOrderTerm
from .planned_replace import PlannedReplace


class PlannedOperations(UniversalBaseModel):
    """
    Structural writes the amendment executes.
    """

    ends: typing.Optional[typing.List[PlannedEnd]] = None
    replaces: typing.Optional[typing.List[PlannedReplace]] = None
    copies: typing.Optional[typing.List[PlannedCopy]] = None
    adds: typing.Optional[typing.List[PlannedAdd]] = None
    order_term: typing_extensions.Annotated[
        typing.Optional[PlannedOrderTerm], FieldMetadata(alias="orderTerm"), pydantic.Field(alias="orderTerm")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
