# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .plan_attribute import PlanAttribute
from .plan_status import PlanStatus


class Plan(UniversalBaseModel):
    id: str
    product_id: typing_extensions.Annotated[str, FieldMetadata(alias="productId"), pydantic.Field(alias="productId")]
    name: typing.Optional[str] = None
    external_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="externalId"), pydantic.Field(alias="externalId")
    ] = None
    supported_currencies: typing_extensions.Annotated[
        typing.List[str], FieldMetadata(alias="supportedCurrencies"), pydantic.Field(alias="supportedCurrencies")
    ]
    is_default: typing_extensions.Annotated[bool, FieldMetadata(alias="isDefault"), pydantic.Field(alias="isDefault")]
    status: PlanStatus
    upgrade_path_order: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="upgradePathOrder"), pydantic.Field(alias="upgradePathOrder")
    ] = None
    archived_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="archivedAt"), pydantic.Field(alias="archivedAt")
    ] = None
    created_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")
    ]
    updated_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="updatedAt"), pydantic.Field(alias="updatedAt")
    ]
    attributes: typing.List[PlanAttribute]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
