# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .credit_benefit_output import CreditBenefitOutput
from .pricing_output import PricingOutput


class PricingResponse(UniversalBaseModel):
    product_attribute_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="productAttributeId"), pydantic.Field(alias="productAttributeId")
    ]
    name: str
    pricing: typing.Optional[PricingOutput] = None
    credit_benefits: typing_extensions.Annotated[
        typing.List[CreditBenefitOutput], FieldMetadata(alias="creditBenefits"), pydantic.Field(alias="creditBenefits")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
