# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .pricing_output_pricing_type import PricingOutputPricingType
from .pricing_price_point_output import PricingPricePointOutput


class PricingOutput(UniversalBaseModel):
    pricing_type: typing_extensions.Annotated[
        PricingOutputPricingType, FieldMetadata(alias="pricingType"), pydantic.Field(alias="pricingType")
    ]
    charge_type: typing_extensions.Annotated[str, FieldMetadata(alias="chargeType"), pydantic.Field(alias="chargeType")]
    pricing_model: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="pricingModel"), pydantic.Field(alias="pricingModel")
    ] = None
    event_name: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="eventName"), pydantic.Field(alias="eventName")
    ] = None
    billing_frequency: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="billingFrequency"), pydantic.Field(alias="billingFrequency")
    ] = None
    billing_type: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="billingType"), pydantic.Field(alias="billingType")
    ] = None
    credits_currency_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="creditsCurrencyId"), pydantic.Field(alias="creditsCurrencyId")
    ] = None
    credit_cost: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="creditCost"), pydantic.Field(alias="creditCost")
    ] = None
    unit_value: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="unitValue"), pydantic.Field(alias="unitValue")
    ] = None
    percentage_value: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="percentageValue"), pydantic.Field(alias="percentageValue")
    ] = None
    cost_plus_multiplier: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="costPlusMultiplier"), pydantic.Field(alias="costPlusMultiplier")
    ] = None
    price_points: typing_extensions.Annotated[
        typing.List[PricingPricePointOutput], FieldMetadata(alias="pricePoints"), pydantic.Field(alias="pricePoints")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
