# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .product_credit_benefit_output import ProductCreditBenefitOutput
from .product_pricing_output import ProductPricingOutput


class ProductAttributeOutput(UniversalBaseModel):
    product_attribute_id: typing_extensions.Annotated[
        str, FieldMetadata(alias="productAttributeId"), pydantic.Field(alias="productAttributeId")
    ]
    name: str
    active: bool
    pricing: typing.Optional[ProductPricingOutput] = None
    credit_benefits: typing_extensions.Annotated[
        typing.List[ProductCreditBenefitOutput],
        FieldMetadata(alias="creditBenefits"),
        pydantic.Field(alias="creditBenefits"),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
