# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .product_recurring_percent_of_total_input_billing_frequency import (
    ProductRecurringPercentOfTotalInputBillingFrequency,
)
from .product_recurring_percent_of_total_input_billing_type import ProductRecurringPercentOfTotalInputBillingType
from .product_simple_price_point import ProductSimplePricePoint


class ProductRecurringPercentOfTotalInput(UniversalBaseModel):
    percentage_value: typing_extensions.Annotated[
        float, FieldMetadata(alias="percentageValue"), pydantic.Field(alias="percentageValue")
    ]
    billing_frequency: typing_extensions.Annotated[
        ProductRecurringPercentOfTotalInputBillingFrequency,
        FieldMetadata(alias="billingFrequency"),
        pydantic.Field(alias="billingFrequency"),
    ]
    billing_frequency_custom_months: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="billingFrequencyCustomMonths"),
        pydantic.Field(alias="billingFrequencyCustomMonths"),
    ] = None
    billing_type: typing_extensions.Annotated[
        typing.Optional[ProductRecurringPercentOfTotalInputBillingType],
        FieldMetadata(alias="billingType"),
        pydantic.Field(alias="billingType"),
    ] = None
    price_points: typing_extensions.Annotated[
        typing.Optional[typing.List[ProductSimplePricePoint]],
        FieldMetadata(alias="pricePoints"),
        pydantic.Field(alias="pricePoints"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
