# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class RotateWebhookSecretResponse(UniversalBaseModel):
    signing_secret: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="signingSecret"),
        pydantic.Field(
            alias="signingSecret",
            description="The newly minted org-scoped signing secret. Returned exactly once — store it now; subsequent reads will not return it.",
        ),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
