# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .attribution import Attribution
from .customer_attribution import CustomerAttribution


class Signal(UniversalBaseModel):
    event_name: typing_extensions.Annotated[str, FieldMetadata(alias="eventName"), pydantic.Field(alias="eventName")]
    customer: CustomerAttribution
    attribution: typing.Optional[Attribution] = None
    timestamp: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    True event timestamp in RFC3339 format with timezone (e.g. 2026-01-31T23:00:00Z)
    """

    data: typing.Optional[typing.Dict[str, typing.Any]] = None
    idempotency_key: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="idempotencyKey"), pydantic.Field(alias="idempotencyKey")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
