# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class TokenUsage(UniversalBaseModel):
    input_tokens: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="inputTokens"),
        pydantic.Field(
            alias="inputTokens",
            description="Non-cached input tokens. Matches Anthropic's `input_tokens` semantic (does not include cached or cache-creation tokens).",
        ),
    ] = None
    output_tokens: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="outputTokens"),
        pydantic.Field(alias="outputTokens", description="Output tokens generated by the model."),
    ] = None
    cache_read_input_tokens: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="cacheReadInputTokens"),
        pydantic.Field(alias="cacheReadInputTokens", description="Input tokens served from cache (cache hit)."),
    ] = None
    cache_creation_input_tokens: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="cacheCreationInputTokens"),
        pydantic.Field(
            alias="cacheCreationInputTokens",
            description="Input tokens written to cache on this request (Anthropic prompt caching).",
        ),
    ] = None
    reasoning_output_tokens: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="reasoningOutputTokens"),
        pydantic.Field(
            alias="reasoningOutputTokens",
            description="Reasoning tokens emitted by reasoning models (o1/o3, Claude extended thinking).",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
