# This file was auto-generated by Fern from our API Definition.

import typing

UpdatePricingIntentTreatment = typing.Union[
    typing.Literal["none", "prorate", "signalsFromAmendment", "allSignalsInPeriod"], typing.Any
]
