# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .update_line_term_intent_treatment import UpdateLineTermIntentTreatment


class UpdateLineTermIntent(UniversalBaseModel):
    order_line_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="orderLineId"),
        pydantic.Field(alias="orderLineId", description="Line UUID from the options response."),
    ]
    new_end_date: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="newEndDate"),
        pydantic.Field(alias="newEndDate", description="New line end date (RFC 3339 with offset)."),
    ]
    treatment: typing.Optional[UpdateLineTermIntentTreatment] = pydantic.Field(default=None)
    """
    Recurring charges pick next-cycle vs settle-now. Usage price changes pick new usage only vs the whole current period.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
