# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .update_pricing_intent_treatment import UpdatePricingIntentTreatment


class UpdatePricingIntent(UniversalBaseModel):
    order_line_attribute_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="orderLineAttributeId"),
        pydantic.Field(
            alias="orderLineAttributeId",
            description="Attribute UUID from the options response. Not the order display id.",
        ),
    ]
    new_unit_price_minor: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="newUnitPriceMinor"),
        pydantic.Field(
            alias="newUnitPriceMinor",
            description="New unit price. Prefer this over `newPricing` when you are only changing the rate. Amount in cents (minor currency units).",
        ),
    ] = None
    new_pricing: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, typing.Any]],
        FieldMetadata(alias="newPricing"),
        pydantic.Field(
            alias="newPricing",
            description="Full pricing JSON. Prefer `addFromCatalog` or `newUnitPriceMinor` unless you are replacing the pricing shape.",
        ),
    ] = None
    new_quantity: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="newQuantity"),
        pydantic.Field(alias="newQuantity", description="Optional quantity change in the same intent."),
    ] = None
    treatment: typing.Optional[UpdatePricingIntentTreatment] = pydantic.Field(default=None)
    """
    Recurring charges pick next-cycle vs settle-now. Usage price changes pick new usage only vs the whole current period.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
