# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .custom_view_filter import CustomViewFilter
from .custom_view_query import CustomViewQuery
from .validate_custom_view_request_period import ValidateCustomViewRequestPeriod
from .validate_custom_view_request_scope import ValidateCustomViewRequestScope


class ValidateCustomViewRequest(UniversalBaseModel):
    queries: typing.Optional[typing.List[CustomViewQuery]] = pydantic.Field(default=None)
    """
    Query list to validate (same shape and gates as createCustomView).
    """

    render_bundle: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="renderBundle"),
        pydantic.Field(
            alias="renderBundle",
            description="Render bundle to validate (same gates as createCustomView: size cap, self-contained, not truncated, paid:data listener).",
        ),
    ] = None
    period: typing.Optional[ValidateCustomViewRequestPeriod] = pydantic.Field(default=None)
    """
    Period to validate together with the queries (required when a query uses the {period_start}/{period_end} placeholders).
    """

    filters: typing.Optional[typing.List[CustomViewFilter]] = pydantic.Field(default=None)
    """
    Filter declarations to validate together with the queries (required for every {filter_<name>:String} placeholder they reference).
    """

    scope: typing.Optional[ValidateCustomViewRequestScope] = pydantic.Field(default=None)
    """
    The scope the view will be created with (default 'customer'). Customer-scoped SQL is compiled against the per-customer analytics views (which cannot read org-wide analytics.* directly), matching how it runs at embed time; pass 'organization' for an org-wide view.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
