# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .value_metric_formula_variable_format import ValueMetricFormulaVariableFormat
from .value_metric_formula_variable_format_unit import ValueMetricFormulaVariableFormatUnit
from .value_metric_formula_variable_type import ValueMetricFormulaVariableType


class ValueMetricFormulaVariable(UniversalBaseModel):
    id: str
    label: str
    type: typing.Optional[ValueMetricFormulaVariableType] = None
    description: typing.Optional[str] = None
    format: typing.Optional[ValueMetricFormulaVariableFormat] = pydantic.Field(default=None)
    """
    Display-only hint. 'percent' renders a stored 0.02 as 2%. 'duration' requires formatUnit. Calculations always use the stored raw value.
    """

    format_unit: typing_extensions.Annotated[
        typing.Optional[ValueMetricFormulaVariableFormatUnit],
        FieldMetadata(alias="formatUnit"),
        pydantic.Field(alias="formatUnit"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
