# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .value_model_content_overrides_item_additional_signals_item import (
    ValueModelContentOverridesItemAdditionalSignalsItem,
)
from .value_model_content_overrides_item_monetary_conversion_overrides_value import (
    ValueModelContentOverridesItemMonetaryConversionOverridesValue,
)
from .value_model_content_overrides_item_scope import ValueModelContentOverridesItemScope
from .value_model_content_overrides_item_signal_overrides_value import (
    ValueModelContentOverridesItemSignalOverridesValue,
)
from .value_model_content_overrides_item_value_type_overrides_value import (
    ValueModelContentOverridesItemValueTypeOverridesValue,
)


class ValueModelContentOverridesItem(UniversalBaseModel):
    id: str
    label: str
    scope: ValueModelContentOverridesItemScope
    currency: typing.Optional[str] = None
    signal_overrides: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, ValueModelContentOverridesItemSignalOverridesValue]],
        FieldMetadata(alias="signalOverrides"),
        pydantic.Field(alias="signalOverrides"),
    ] = None
    value_type_overrides: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, ValueModelContentOverridesItemValueTypeOverridesValue]],
        FieldMetadata(alias="valueTypeOverrides"),
        pydantic.Field(
            alias="valueTypeOverrides",
            description="Per-value-metric formula variable overrides, keyed by value type slug. Scoped to the named metric's formulas only — unlike signalOverrides (keyed by event name), a binding event shared with other metrics does not leak these values into them. When both shapes set the same variable, the value here wins.",
        ),
    ] = None
    additional_signals: typing_extensions.Annotated[
        typing.Optional[typing.List[ValueModelContentOverridesItemAdditionalSignalsItem]],
        FieldMetadata(alias="additionalSignals"),
        pydantic.Field(alias="additionalSignals"),
    ] = None
    monetary_conversion_overrides: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, ValueModelContentOverridesItemMonetaryConversionOverridesValue]],
        FieldMetadata(alias="monetaryConversionOverrides"),
        pydantic.Field(alias="monetaryConversionOverrides"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
