# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .value_model_authoring_guide_examples_item import ValueModelAuthoringGuideExamplesItem


class ValueModelAuthoringGuide(UniversalBaseModel):
    overview: str
    workflow: typing.List[str]
    categories: typing.Dict[str, str]
    units: str
    formulas: typing.List[str]
    signal_binding: typing_extensions.Annotated[
        str, FieldMetadata(alias="signalBinding"), pydantic.Field(alias="signalBinding")
    ]
    monetary_conversion: typing_extensions.Annotated[
        str, FieldMetadata(alias="monetaryConversion"), pydantic.Field(alias="monetaryConversion")
    ]
    concurrency: str
    limitations: typing.List[str]
    examples: typing.List[ValueModelAuthoringGuideExamplesItem]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
