# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class ValueMetricMonetaryConversion(UniversalBaseModel):
    value_per_unit: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="valuePerUnit"),
        pydantic.Field(
            alias="valuePerUnit", description="Money earned or saved per one unit. Expands to 'unit_value * rate'."
        ),
    ]
    label: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name for the rate variable on customer-facing calculation strips. Defaults to 'rate'.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
