# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .value_model_content_value_types_item_calculation_timeline_item_calculation_unit_type_type import (
    ValueModelContentValueTypesItemCalculationTimelineItemCalculationUnitTypeType,
)


class ValueModelContentValueTypesItemCalculationTimelineItemCalculationUnitType(UniversalBaseModel):
    type: ValueModelContentValueTypesItemCalculationTimelineItemCalculationUnitTypeType
    unit: str
    unit_display: str

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
