# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class ValueReceiptSummary(UniversalBaseModel):
    id: str
    status: str
    public_url_token: typing_extensions.Annotated[
        str, FieldMetadata(alias="publicUrlToken"), pydantic.Field(alias="publicUrlToken")
    ]
    public_url: typing_extensions.Annotated[str, FieldMetadata(alias="publicUrl"), pydantic.Field(alias="publicUrl")]
    is_published: typing_extensions.Annotated[
        bool, FieldMetadata(alias="isPublished"), pydantic.Field(alias="isPublished")
    ]
    customer_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="customerId"), pydantic.Field(alias="customerId")
    ] = None
    customer_name: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="customerName"), pydantic.Field(alias="customerName")
    ] = None
    customer_external_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="customerExternalId"), pydantic.Field(alias="customerExternalId")
    ] = None
    order_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="orderId"), pydantic.Field(alias="orderId")
    ] = None
    product_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="productId"), pydantic.Field(alias="productId")
    ] = None
    currency: str
    start_date: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="startDate"), pydantic.Field(alias="startDate")
    ] = None
    end_date: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="endDate"), pydantic.Field(alias="endDate")
    ] = None
    total_delivered_value: typing_extensions.Annotated[
        typing.Optional[float], FieldMetadata(alias="totalDeliveredValue"), pydantic.Field(alias="totalDeliveredValue")
    ] = None
    archived_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="archivedAt"), pydantic.Field(alias="archivedAt")
    ] = None
    created_at: typing_extensions.Annotated[
        dt.datetime, FieldMetadata(alias="createdAt"), pydantic.Field(alias="createdAt")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
