# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .value_model_content_value_types_item_calculation_timeline_item_calculation_monetary_conversion import (
    ValueModelContentValueTypesItemCalculationTimelineItemCalculationMonetaryConversion,
)
from .value_model_content_value_types_item_calculation_timeline_item_calculation_unit import (
    ValueModelContentValueTypesItemCalculationTimelineItemCalculationUnit,
)


class ValueModelContentValueTypesItemCalculationTimelineItemCalculation(UniversalBaseModel):
    unit: ValueModelContentValueTypesItemCalculationTimelineItemCalculationUnit
    monetary_conversion: typing_extensions.Annotated[
        typing.Optional[ValueModelContentValueTypesItemCalculationTimelineItemCalculationMonetaryConversion],
        FieldMetadata(alias="monetaryConversion"),
        pydantic.Field(alias="monetaryConversion"),
    ] = None
    formula_ids: typing_extensions.Annotated[
        typing.List[str], FieldMetadata(alias="formulaIds"), pydantic.Field(alias="formulaIds")
    ]
    signal_event_names: typing_extensions.Annotated[
        typing.List[str], FieldMetadata(alias="signalEventNames"), pydantic.Field(alias="signalEventNames")
    ]
    segment_table_ids: typing_extensions.Annotated[
        typing.List[str], FieldMetadata(alias="segmentTableIds"), pydantic.Field(alias="segmentTableIds")
    ]
    override_ids: typing_extensions.Annotated[
        typing.List[str], FieldMetadata(alias="overrideIds"), pydantic.Field(alias="overrideIds")
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
