# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .value_model_content_formulas_item_conditions_item_operator import (
    ValueModelContentFormulasItemConditionsItemOperator,
)
from .value_model_content_formulas_item_conditions_item_result import ValueModelContentFormulasItemConditionsItemResult
from .value_model_content_formulas_item_conditions_item_value import ValueModelContentFormulasItemConditionsItemValue


class ValueModelContentFormulasItemConditionsItem(UniversalBaseModel):
    field: str
    operator: ValueModelContentFormulasItemConditionsItemOperator
    value: ValueModelContentFormulasItemConditionsItemValue
    result: ValueModelContentFormulasItemConditionsItemResult

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
