# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .value_model_content_value_types_item_monetary_conversion_conditions_item import (
    ValueModelContentValueTypesItemMonetaryConversionConditionsItem,
)
from .value_model_content_value_types_item_monetary_conversion_variables_item import (
    ValueModelContentValueTypesItemMonetaryConversionVariablesItem,
)


class ValueModelContentValueTypesItemMonetaryConversion(UniversalBaseModel):
    expression: str
    variables: typing.Optional[typing.List[ValueModelContentValueTypesItemMonetaryConversionVariablesItem]] = None
    conditions: typing.Optional[typing.List[ValueModelContentValueTypesItemMonetaryConversionConditionsItem]] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
