# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .value_metric_summary_monetary_conversion import ValueMetricSummaryMonetaryConversion
from .value_metric_unit import ValueMetricUnit


class ValueMetricSummary(UniversalBaseModel):
    slug: str
    name: str
    category: typing.Optional[str] = None
    unit: ValueMetricUnit
    description: typing.Optional[str] = None
    archived_at: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="archivedAt"), pydantic.Field(alias="archivedAt")
    ] = None
    monetary_conversion: typing_extensions.Annotated[
        typing.Optional[ValueMetricSummaryMonetaryConversion],
        FieldMetadata(alias="monetaryConversion"),
        pydantic.Field(alias="monetaryConversion"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
