# This file was auto-generated by Fern from our API Definition.

import typing

ValueModelContentValueTypesItemMonetaryConversionConditionsItemOperator = typing.Union[
    typing.Literal["gte", "gt", "lt", "lte", "eq", "neq", "contains", "eq_string", "eq_bool"], typing.Any
]
