# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .value_model_content_formulas_item_conditions_item import ValueModelContentFormulasItemConditionsItem
from .value_model_content_formulas_item_default_result import ValueModelContentFormulasItemDefaultResult
from .value_model_content_formulas_item_variables_item import ValueModelContentFormulasItemVariablesItem


class ValueModelContentFormulasItem(UniversalBaseModel):
    id: str
    value_type_slug: typing_extensions.Annotated[
        str, FieldMetadata(alias="valueTypeSlug"), pydantic.Field(alias="valueTypeSlug")
    ]
    label: str
    description: typing.Optional[str] = None
    variables: typing.List[ValueModelContentFormulasItemVariablesItem]
    expression: str
    conditions: typing.Optional[typing.List[ValueModelContentFormulasItemConditionsItem]] = None
    default_result: typing_extensions.Annotated[
        typing.Optional[ValueModelContentFormulasItemDefaultResult],
        FieldMetadata(alias="defaultResult"),
        pydantic.Field(alias="defaultResult"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
