# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .webhook_delivery_status import WebhookDeliveryStatus
from .webhook_update_response_name import WebhookUpdateResponseName


class WebhookUpdateResponse(UniversalBaseModel):
    id: str
    name: WebhookUpdateResponseName
    description: str
    enabled: bool
    url: typing.Optional[str] = None
    last_sent_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="lastSentAt"), pydantic.Field(alias="lastSentAt")
    ] = None
    last_status: typing_extensions.Annotated[
        typing.Optional[WebhookDeliveryStatus], FieldMetadata(alias="lastStatus"), pydantic.Field(alias="lastStatus")
    ] = None
    signing_secret: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="signingSecret"),
        pydantic.Field(
            alias="signingSecret",
            description="Included on the response of the first save that produced a signing key for this organization (when no webhook had a key yet). Store it now — subsequent reads will not return it; rotate to mint a new one if you lose it.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
