# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.empty_response import EmptyResponse
from ..types.payment_method import PaymentMethod
from ..types.payment_method_list_response import PaymentMethodListResponse
from ..types.payment_method_setup import PaymentMethodSetup
from .raw_client import AsyncRawPaymentMethodsClient, RawPaymentMethodsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class PaymentMethodsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPaymentMethodsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPaymentMethodsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPaymentMethodsClient
        """
        return self._raw_client

    def list_payment_methods(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        customer_id: typing.Optional[str] = None,
        external_customer_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaymentMethodListResponse:
        """
        Lists the payment methods saved for a customer

        Parameters
        ----------
        limit : typing.Optional[int]

        offset : typing.Optional[int]

        customer_id : typing.Optional[str]
            Filter by Paid customer ID.

        external_customer_id : typing.Optional[str]
            Filter by your external customer ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaymentMethodListResponse
            200

        Examples
        --------
        from paid import Paid

        client = Paid(
            token="YOUR_TOKEN",
        )
        client.payment_methods.list_payment_methods(
            customer_id="cus_1234abcd",
        )
        """
        _response = self._raw_client.list_payment_methods(
            limit=limit,
            offset=offset,
            customer_id=customer_id,
            external_customer_id=external_customer_id,
            request_options=request_options,
        )
        return _response.data

    def create_payment_method(
        self,
        *,
        confirmation_token: str,
        customer_id: typing.Optional[str] = OMIT,
        external_customer_id: typing.Optional[str] = OMIT,
        return_url: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaymentMethodSetup:
        """
        Starts attaching a payment method to a customer by exchanging a client-side confirmation token for a setup intent. Complete any additional authentication client-side using the returned client secret.

        Parameters
        ----------
        confirmation_token : str
            Confirmation token generated client-side by the payment processor's elements (e.g. a Stripe ConfirmationToken ID).

        customer_id : typing.Optional[str]
            Paid customer ID to attach the payment method to.

        external_customer_id : typing.Optional[str]
            Your external customer ID to attach the payment method to.

        return_url : typing.Optional[str]
            URL the customer is redirected to after completing any additional authentication step (e.g. 3-D Secure).

        metadata : typing.Optional[typing.Dict[str, str]]
            Key-value metadata stored on the setup intent.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaymentMethodSetup
            201

        Examples
        --------
        from paid import Paid

        client = Paid(
            token="YOUR_TOKEN",
        )
        client.payment_methods.create_payment_method(
            confirmation_token="ctoken_1NXWPnLkdIwHu7ix",
        )
        """
        _response = self._raw_client.create_payment_method(
            confirmation_token=confirmation_token,
            customer_id=customer_id,
            external_customer_id=external_customer_id,
            return_url=return_url,
            metadata=metadata,
            request_options=request_options,
        )
        return _response.data

    def get_payment_method(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> PaymentMethod:
        """
        Get a payment method by its ID

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaymentMethod
            200

        Examples
        --------
        from paid import Paid

        client = Paid(
            token="YOUR_TOKEN",
        )
        client.payment_methods.get_payment_method(
            id="id",
        )
        """
        _response = self._raw_client.get_payment_method(id, request_options=request_options)
        return _response.data

    def delete_payment_method(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> EmptyResponse:
        """
        Detaches a payment method from the customer and removes it from the payment processor

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EmptyResponse
            200

        Examples
        --------
        from paid import Paid

        client = Paid(
            token="YOUR_TOKEN",
        )
        client.payment_methods.delete_payment_method(
            id="id",
        )
        """
        _response = self._raw_client.delete_payment_method(id, request_options=request_options)
        return _response.data

    def update_default_payment_method(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PaymentMethod:
        """
        Makes this payment method the customer's default for future charges

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaymentMethod
            200

        Examples
        --------
        from paid import Paid

        client = Paid(
            token="YOUR_TOKEN",
        )
        client.payment_methods.update_default_payment_method(
            id="id",
        )
        """
        _response = self._raw_client.update_default_payment_method(id, request_options=request_options)
        return _response.data


class AsyncPaymentMethodsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPaymentMethodsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPaymentMethodsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPaymentMethodsClient
        """
        return self._raw_client

    async def list_payment_methods(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        customer_id: typing.Optional[str] = None,
        external_customer_id: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaymentMethodListResponse:
        """
        Lists the payment methods saved for a customer

        Parameters
        ----------
        limit : typing.Optional[int]

        offset : typing.Optional[int]

        customer_id : typing.Optional[str]
            Filter by Paid customer ID.

        external_customer_id : typing.Optional[str]
            Filter by your external customer ID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaymentMethodListResponse
            200

        Examples
        --------
        import asyncio

        from paid import AsyncPaid

        client = AsyncPaid(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.payment_methods.list_payment_methods(
                customer_id="cus_1234abcd",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_payment_methods(
            limit=limit,
            offset=offset,
            customer_id=customer_id,
            external_customer_id=external_customer_id,
            request_options=request_options,
        )
        return _response.data

    async def create_payment_method(
        self,
        *,
        confirmation_token: str,
        customer_id: typing.Optional[str] = OMIT,
        external_customer_id: typing.Optional[str] = OMIT,
        return_url: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, str]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PaymentMethodSetup:
        """
        Starts attaching a payment method to a customer by exchanging a client-side confirmation token for a setup intent. Complete any additional authentication client-side using the returned client secret.

        Parameters
        ----------
        confirmation_token : str
            Confirmation token generated client-side by the payment processor's elements (e.g. a Stripe ConfirmationToken ID).

        customer_id : typing.Optional[str]
            Paid customer ID to attach the payment method to.

        external_customer_id : typing.Optional[str]
            Your external customer ID to attach the payment method to.

        return_url : typing.Optional[str]
            URL the customer is redirected to after completing any additional authentication step (e.g. 3-D Secure).

        metadata : typing.Optional[typing.Dict[str, str]]
            Key-value metadata stored on the setup intent.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaymentMethodSetup
            201

        Examples
        --------
        import asyncio

        from paid import AsyncPaid

        client = AsyncPaid(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.payment_methods.create_payment_method(
                confirmation_token="ctoken_1NXWPnLkdIwHu7ix",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_payment_method(
            confirmation_token=confirmation_token,
            customer_id=customer_id,
            external_customer_id=external_customer_id,
            return_url=return_url,
            metadata=metadata,
            request_options=request_options,
        )
        return _response.data

    async def get_payment_method(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PaymentMethod:
        """
        Get a payment method by its ID

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaymentMethod
            200

        Examples
        --------
        import asyncio

        from paid import AsyncPaid

        client = AsyncPaid(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.payment_methods.get_payment_method(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_payment_method(id, request_options=request_options)
        return _response.data

    async def delete_payment_method(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> EmptyResponse:
        """
        Detaches a payment method from the customer and removes it from the payment processor

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EmptyResponse
            200

        Examples
        --------
        import asyncio

        from paid import AsyncPaid

        client = AsyncPaid(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.payment_methods.delete_payment_method(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_payment_method(id, request_options=request_options)
        return _response.data

    async def update_default_payment_method(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> PaymentMethod:
        """
        Makes this payment method the customer's default for future charges

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PaymentMethod
            200

        Examples
        --------
        import asyncio

        from paid import AsyncPaid

        client = AsyncPaid(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.payment_methods.update_default_payment_method(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_default_payment_method(id, request_options=request_options)
        return _response.data
