# This file was auto-generated by Fern from our API Definition.

import typing

GetInvoicesIdResponsePaymentStatus = typing.Union[
    typing.Literal["pending", "paid", "partiallyPaid", "overdue", "error"], typing.Any
]
