# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .get_invoices_id_lines_response_data_item import GetInvoicesIdLinesResponseDataItem
from .get_invoices_id_lines_response_pagination import GetInvoicesIdLinesResponsePagination


class GetInvoicesIdLinesResponse(UniversalBaseModel):
    data: typing.List[GetInvoicesIdLinesResponseDataItem]
    pagination: GetInvoicesIdLinesResponsePagination

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
