# This file was auto-generated by Fern from our API Definition.

import typing

PutInvoicesIdResponseTaxStatus = typing.Union[
    typing.Literal["not_applicable", "calculated", "committed", "failed", "voided"], typing.Any
]
