# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.bulk_signals_response import BulkSignalsResponse
from ..types.signal import Signal
from .raw_client import AsyncRawSignalsClient, RawSignalsClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class SignalsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawSignalsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawSignalsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawSignalsClient
        """
        return self._raw_client

    def create_signals(
        self, *, signals: typing.Sequence[Signal], request_options: typing.Optional[RequestOptions] = None
    ) -> BulkSignalsResponse:
        """
        Create multiple signals (usage events) in a single request. Each signal must include a customer attribution (either customerId or externalCustomerId) and a product attribution (either productId or externalProductId).

        Parameters
        ----------
        signals : typing.Sequence[Signal]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BulkSignalsResponse
            200

        Examples
        --------
        from paid import CustomerById, Paid, Signal

        client = Paid(
            token="YOUR_TOKEN",
        )
        client.signals.create_signals(
            signals=[
                Signal(
                    event_name="eventName",
                    customer=CustomerById(
                        customer_id="customerId",
                    ),
                )
            ],
        )
        """
        _response = self._raw_client.create_signals(signals=signals, request_options=request_options)
        return _response.data


class AsyncSignalsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawSignalsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawSignalsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawSignalsClient
        """
        return self._raw_client

    async def create_signals(
        self, *, signals: typing.Sequence[Signal], request_options: typing.Optional[RequestOptions] = None
    ) -> BulkSignalsResponse:
        """
        Create multiple signals (usage events) in a single request. Each signal must include a customer attribution (either customerId or externalCustomerId) and a product attribution (either productId or externalProductId).

        Parameters
        ----------
        signals : typing.Sequence[Signal]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BulkSignalsResponse
            200

        Examples
        --------
        import asyncio

        from paid import AsyncPaid, CustomerById, Signal

        client = AsyncPaid(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.signals.create_signals(
                signals=[
                    Signal(
                        event_name="eventName",
                        customer=CustomerById(
                            customer_id="customerId",
                        ),
                    )
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_signals(signals=signals, request_options=request_options)
        return _response.data
