# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .products_update_by_external_id_response_product_attribute_item_pricing_price_points_value_tiers_item import (
    ProductsUpdateByExternalIdResponseProductAttributeItemPricingPricePointsValueTiersItem,
)


class ProductsUpdateByExternalIdResponseProductAttributeItemPricingPricePointsValue(UniversalBaseModel):
    unit_price: typing_extensions.Annotated[typing.Optional[float], FieldMetadata(alias="unitPrice")] = None
    min_quantity: typing_extensions.Annotated[typing.Optional[float], FieldMetadata(alias="minQuantity")] = None
    included_quantity: typing_extensions.Annotated[typing.Optional[float], FieldMetadata(alias="includedQuantity")] = (
        None
    )
    tiers: typing.Optional[
        typing.List[ProductsUpdateByExternalIdResponseProductAttributeItemPricingPricePointsValueTiersItem]
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
