# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .products_update_request_product_attribute_item_pricing_billing_frequency import (
    ProductsUpdateRequestProductAttributeItemPricingBillingFrequency,
)
from .products_update_request_product_attribute_item_pricing_charge_type import (
    ProductsUpdateRequestProductAttributeItemPricingChargeType,
)
from .products_update_request_product_attribute_item_pricing_price_points_value import (
    ProductsUpdateRequestProductAttributeItemPricingPricePointsValue,
)
from .products_update_request_product_attribute_item_pricing_pricing_model import (
    ProductsUpdateRequestProductAttributeItemPricingPricingModel,
)


class ProductsUpdateRequestProductAttributeItemPricing(UniversalBaseModel):
    event_name: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="eventName")] = None
    taxable: bool
    credit_cost: typing_extensions.Annotated[typing.Optional[float], FieldMetadata(alias="creditCost")] = None
    charge_type: typing_extensions.Annotated[
        ProductsUpdateRequestProductAttributeItemPricingChargeType, FieldMetadata(alias="chargeType")
    ]
    pricing_model: typing_extensions.Annotated[
        ProductsUpdateRequestProductAttributeItemPricingPricingModel, FieldMetadata(alias="pricingModel")
    ]
    billing_frequency: typing_extensions.Annotated[
        ProductsUpdateRequestProductAttributeItemPricingBillingFrequency, FieldMetadata(alias="billingFrequency")
    ]
    price_points: typing_extensions.Annotated[
        typing.Dict[str, ProductsUpdateRequestProductAttributeItemPricingPricePointsValue],
        FieldMetadata(alias="pricePoints"),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
