# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .products_get_by_external_id_response_product_attribute_item_pricing import (
    ProductsGetByExternalIdResponseProductAttributeItemPricing,
)


class ProductsGetByExternalIdResponseProductAttributeItem(UniversalBaseModel):
    name: str
    active: bool
    pricing: ProductsGetByExternalIdResponseProductAttributeItemPricing

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
