# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from .products_get_by_external_id_response_product_attribute_item_pricing_billing_frequency import (
    ProductsGetByExternalIdResponseProductAttributeItemPricingBillingFrequency,
)
from .products_get_by_external_id_response_product_attribute_item_pricing_charge_type import (
    ProductsGetByExternalIdResponseProductAttributeItemPricingChargeType,
)
from .products_get_by_external_id_response_product_attribute_item_pricing_price_points_value import (
    ProductsGetByExternalIdResponseProductAttributeItemPricingPricePointsValue,
)
from .products_get_by_external_id_response_product_attribute_item_pricing_pricing_model import (
    ProductsGetByExternalIdResponseProductAttributeItemPricingPricingModel,
)


class ProductsGetByExternalIdResponseProductAttributeItemPricing(UniversalBaseModel):
    event_name: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="eventName")] = None
    taxable: bool
    credit_cost: typing_extensions.Annotated[typing.Optional[float], FieldMetadata(alias="creditCost")] = None
    charge_type: typing_extensions.Annotated[
        ProductsGetByExternalIdResponseProductAttributeItemPricingChargeType, FieldMetadata(alias="chargeType")
    ]
    pricing_model: typing_extensions.Annotated[
        ProductsGetByExternalIdResponseProductAttributeItemPricingPricingModel, FieldMetadata(alias="pricingModel")
    ]
    billing_frequency: typing_extensions.Annotated[
        ProductsGetByExternalIdResponseProductAttributeItemPricingBillingFrequency,
        FieldMetadata(alias="billingFrequency"),
    ]
    price_points: typing_extensions.Annotated[
        typing.Dict[str, ProductsGetByExternalIdResponseProductAttributeItemPricingPricePointsValue],
        FieldMetadata(alias="pricePoints"),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
