# This file was auto-generated by Fern from our API Definition.

import typing

ProductsCreateResponseProductAttributeItemPricingBillingFrequency = typing.Union[
    typing.Literal["monthly", "quarterly", "annual"], typing.Any
]
