# This file was auto-generated by Fern from our API Definition.

import typing

ProductsGetResponseProductAttributeItemPricingChargeType = typing.Union[
    typing.Literal["oneTime", "recurring", "usage", "seatBased"], typing.Any
]
