# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.plan import Plan
from ..types.plan_attribute_input import PlanAttributeInput
from ..types.plan_list_response import PlanListResponse
from ..types.plan_upgrade_path_group import PlanUpgradePathGroup
from ..types.plan_upgrade_path_response import PlanUpgradePathResponse
from ..types.update_plan_request_status import UpdatePlanRequestStatus
from .raw_client import AsyncRawPlansClient, RawPlansClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class PlansClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawPlansClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawPlansClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawPlansClient
        """
        return self._raw_client

    def list_plans(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        product_id: typing.Optional[str] = None,
        external_product_id: typing.Optional[str] = None,
        include_archived: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PlanListResponse:
        """
        Returns plans for your organization, including archived plans by default, optionally filtered to a product.

        Parameters
        ----------
        limit : typing.Optional[int]

        offset : typing.Optional[int]

        product_id : typing.Optional[str]

        external_product_id : typing.Optional[str]

        include_archived : typing.Optional[bool]
            Whether to include archived plans in the response. Defaults to true.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PlanListResponse
            200

        Examples
        --------
        from paid import Paid

        client = Paid(
            token="YOUR_TOKEN",
        )
        client.plans.list_plans()
        """
        _response = self._raw_client.list_plans(
            limit=limit,
            offset=offset,
            product_id=product_id,
            external_product_id=external_product_id,
            include_archived=include_archived,
            request_options=request_options,
        )
        return _response.data

    def create_plan(
        self,
        *,
        product_id: str,
        attributes: typing.Sequence[PlanAttributeInput],
        name: typing.Optional[str] = OMIT,
        external_id: typing.Optional[str] = OMIT,
        supported_currencies: typing.Optional[typing.Sequence[str]] = OMIT,
        is_default: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Plan:
        """
        Creates a new plan for a product.

        Parameters
        ----------
        product_id : str
            Paid product ID, for example `prod_abc123`

        attributes : typing.Sequence[PlanAttributeInput]

        name : typing.Optional[str]

        external_id : typing.Optional[str]
            Your stable identifier for this plan

        supported_currencies : typing.Optional[typing.Sequence[str]]

        is_default : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Plan
            201

        Examples
        --------
        from paid import (
            Paid,
            PlanAttributeInput,
            ProductPricingInput_RecurringPerUnit,
            ProductSimplePricePoint,
        )

        client = Paid(
            token="YOUR_TOKEN",
        )
        client.plans.create_plan(
            product_id="productId",
            attributes=[
                PlanAttributeInput(
                    product_attribute_id="productAttributeId",
                    pricing=ProductPricingInput_RecurringPerUnit(
                        billing_frequency="Monthly",
                        price_points=[
                            ProductSimplePricePoint(
                                currency="USD",
                                unit_price=99.0,
                            )
                        ],
                    ),
                )
            ],
        )
        """
        _response = self._raw_client.create_plan(
            product_id=product_id,
            attributes=attributes,
            name=name,
            external_id=external_id,
            supported_currencies=supported_currencies,
            is_default=is_default,
            request_options=request_options,
        )
        return _response.data

    def update_plan_upgrade_path(
        self,
        *,
        product_id: str,
        groups: typing.Sequence[PlanUpgradePathGroup],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PlanUpgradePathResponse:
        """
        Updates upgrade path ordering for plans within a product, grouped by billing frequency.

        Parameters
        ----------
        product_id : str
            Paid product ID, for example `prod_abc123`

        groups : typing.Sequence[PlanUpgradePathGroup]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PlanUpgradePathResponse
            200

        Examples
        --------
        from paid import Paid, PlanUpgradePathGroup

        client = Paid(
            token="YOUR_TOKEN",
        )
        client.plans.update_plan_upgrade_path(
            product_id="productId",
            groups=[
                PlanUpgradePathGroup(
                    plan_ids=["planIds"],
                )
            ],
        )
        """
        _response = self._raw_client.update_plan_upgrade_path(
            product_id=product_id, groups=groups, request_options=request_options
        )
        return _response.data

    def get_plan_by_id(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Plan:
        """
        Get a plan by Paid plan ID.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Plan
            200

        Examples
        --------
        from paid import Paid

        client = Paid(
            token="YOUR_TOKEN",
        )
        client.plans.get_plan_by_id(
            id="id",
        )
        """
        _response = self._raw_client.get_plan_by_id(id, request_options=request_options)
        return _response.data

    def update_plan_by_id(
        self,
        id: str,
        *,
        name: typing.Optional[str] = OMIT,
        external_id: typing.Optional[str] = OMIT,
        supported_currencies: typing.Optional[typing.Sequence[str]] = OMIT,
        is_default: typing.Optional[bool] = OMIT,
        status: typing.Optional[UpdatePlanRequestStatus] = OMIT,
        attributes: typing.Optional[typing.Sequence[PlanAttributeInput]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Plan:
        """
        Update a plan by Paid plan ID. If attributes are provided, they replace the plan's existing attributes. Set status to archive or restore the plan.

        Parameters
        ----------
        id : str

        name : typing.Optional[str]

        external_id : typing.Optional[str]

        supported_currencies : typing.Optional[typing.Sequence[str]]

        is_default : typing.Optional[bool]

        status : typing.Optional[UpdatePlanRequestStatus]
            Set to `archived` to archive this plan, or `active` to restore it.

        attributes : typing.Optional[typing.Sequence[PlanAttributeInput]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Plan
            200

        Examples
        --------
        from paid import Paid

        client = Paid(
            token="YOUR_TOKEN",
        )
        client.plans.update_plan_by_id(
            id="id",
        )
        """
        _response = self._raw_client.update_plan_by_id(
            id,
            name=name,
            external_id=external_id,
            supported_currencies=supported_currencies,
            is_default=is_default,
            status=status,
            attributes=attributes,
            request_options=request_options,
        )
        return _response.data

    def get_plan_by_external_id(
        self, external_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> Plan:
        """
        Get a plan by your external plan ID.

        Parameters
        ----------
        external_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Plan
            200

        Examples
        --------
        from paid import Paid

        client = Paid(
            token="YOUR_TOKEN",
        )
        client.plans.get_plan_by_external_id(
            external_id="externalId",
        )
        """
        _response = self._raw_client.get_plan_by_external_id(external_id, request_options=request_options)
        return _response.data

    def update_plan_by_external_id(
        self,
        external_id_: str,
        *,
        name: typing.Optional[str] = OMIT,
        external_id: typing.Optional[str] = OMIT,
        supported_currencies: typing.Optional[typing.Sequence[str]] = OMIT,
        is_default: typing.Optional[bool] = OMIT,
        status: typing.Optional[UpdatePlanRequestStatus] = OMIT,
        attributes: typing.Optional[typing.Sequence[PlanAttributeInput]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Plan:
        """
        Update a plan by your external plan ID. If attributes are provided, they replace the plan's existing attributes. Set status to archive or restore the plan.

        Parameters
        ----------
        external_id_ : str

        name : typing.Optional[str]

        external_id : typing.Optional[str]

        supported_currencies : typing.Optional[typing.Sequence[str]]

        is_default : typing.Optional[bool]

        status : typing.Optional[UpdatePlanRequestStatus]
            Set to `archived` to archive this plan, or `active` to restore it.

        attributes : typing.Optional[typing.Sequence[PlanAttributeInput]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Plan
            200

        Examples
        --------
        from paid import Paid

        client = Paid(
            token="YOUR_TOKEN",
        )
        client.plans.update_plan_by_external_id(
            external_id_="externalId",
        )
        """
        _response = self._raw_client.update_plan_by_external_id(
            external_id_,
            name=name,
            external_id=external_id,
            supported_currencies=supported_currencies,
            is_default=is_default,
            status=status,
            attributes=attributes,
            request_options=request_options,
        )
        return _response.data


class AsyncPlansClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawPlansClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawPlansClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawPlansClient
        """
        return self._raw_client

    async def list_plans(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        product_id: typing.Optional[str] = None,
        external_product_id: typing.Optional[str] = None,
        include_archived: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PlanListResponse:
        """
        Returns plans for your organization, including archived plans by default, optionally filtered to a product.

        Parameters
        ----------
        limit : typing.Optional[int]

        offset : typing.Optional[int]

        product_id : typing.Optional[str]

        external_product_id : typing.Optional[str]

        include_archived : typing.Optional[bool]
            Whether to include archived plans in the response. Defaults to true.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PlanListResponse
            200

        Examples
        --------
        import asyncio

        from paid import AsyncPaid

        client = AsyncPaid(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.plans.list_plans()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_plans(
            limit=limit,
            offset=offset,
            product_id=product_id,
            external_product_id=external_product_id,
            include_archived=include_archived,
            request_options=request_options,
        )
        return _response.data

    async def create_plan(
        self,
        *,
        product_id: str,
        attributes: typing.Sequence[PlanAttributeInput],
        name: typing.Optional[str] = OMIT,
        external_id: typing.Optional[str] = OMIT,
        supported_currencies: typing.Optional[typing.Sequence[str]] = OMIT,
        is_default: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Plan:
        """
        Creates a new plan for a product.

        Parameters
        ----------
        product_id : str
            Paid product ID, for example `prod_abc123`

        attributes : typing.Sequence[PlanAttributeInput]

        name : typing.Optional[str]

        external_id : typing.Optional[str]
            Your stable identifier for this plan

        supported_currencies : typing.Optional[typing.Sequence[str]]

        is_default : typing.Optional[bool]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Plan
            201

        Examples
        --------
        import asyncio

        from paid import (
            AsyncPaid,
            PlanAttributeInput,
            ProductPricingInput_RecurringPerUnit,
            ProductSimplePricePoint,
        )

        client = AsyncPaid(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.plans.create_plan(
                product_id="productId",
                attributes=[
                    PlanAttributeInput(
                        product_attribute_id="productAttributeId",
                        pricing=ProductPricingInput_RecurringPerUnit(
                            billing_frequency="Monthly",
                            price_points=[
                                ProductSimplePricePoint(
                                    currency="USD",
                                    unit_price=99.0,
                                )
                            ],
                        ),
                    )
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_plan(
            product_id=product_id,
            attributes=attributes,
            name=name,
            external_id=external_id,
            supported_currencies=supported_currencies,
            is_default=is_default,
            request_options=request_options,
        )
        return _response.data

    async def update_plan_upgrade_path(
        self,
        *,
        product_id: str,
        groups: typing.Sequence[PlanUpgradePathGroup],
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PlanUpgradePathResponse:
        """
        Updates upgrade path ordering for plans within a product, grouped by billing frequency.

        Parameters
        ----------
        product_id : str
            Paid product ID, for example `prod_abc123`

        groups : typing.Sequence[PlanUpgradePathGroup]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PlanUpgradePathResponse
            200

        Examples
        --------
        import asyncio

        from paid import AsyncPaid, PlanUpgradePathGroup

        client = AsyncPaid(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.plans.update_plan_upgrade_path(
                product_id="productId",
                groups=[
                    PlanUpgradePathGroup(
                        plan_ids=["planIds"],
                    )
                ],
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_plan_upgrade_path(
            product_id=product_id, groups=groups, request_options=request_options
        )
        return _response.data

    async def get_plan_by_id(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Plan:
        """
        Get a plan by Paid plan ID.

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Plan
            200

        Examples
        --------
        import asyncio

        from paid import AsyncPaid

        client = AsyncPaid(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.plans.get_plan_by_id(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_plan_by_id(id, request_options=request_options)
        return _response.data

    async def update_plan_by_id(
        self,
        id: str,
        *,
        name: typing.Optional[str] = OMIT,
        external_id: typing.Optional[str] = OMIT,
        supported_currencies: typing.Optional[typing.Sequence[str]] = OMIT,
        is_default: typing.Optional[bool] = OMIT,
        status: typing.Optional[UpdatePlanRequestStatus] = OMIT,
        attributes: typing.Optional[typing.Sequence[PlanAttributeInput]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Plan:
        """
        Update a plan by Paid plan ID. If attributes are provided, they replace the plan's existing attributes. Set status to archive or restore the plan.

        Parameters
        ----------
        id : str

        name : typing.Optional[str]

        external_id : typing.Optional[str]

        supported_currencies : typing.Optional[typing.Sequence[str]]

        is_default : typing.Optional[bool]

        status : typing.Optional[UpdatePlanRequestStatus]
            Set to `archived` to archive this plan, or `active` to restore it.

        attributes : typing.Optional[typing.Sequence[PlanAttributeInput]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Plan
            200

        Examples
        --------
        import asyncio

        from paid import AsyncPaid

        client = AsyncPaid(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.plans.update_plan_by_id(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_plan_by_id(
            id,
            name=name,
            external_id=external_id,
            supported_currencies=supported_currencies,
            is_default=is_default,
            status=status,
            attributes=attributes,
            request_options=request_options,
        )
        return _response.data

    async def get_plan_by_external_id(
        self, external_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> Plan:
        """
        Get a plan by your external plan ID.

        Parameters
        ----------
        external_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Plan
            200

        Examples
        --------
        import asyncio

        from paid import AsyncPaid

        client = AsyncPaid(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.plans.get_plan_by_external_id(
                external_id="externalId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_plan_by_external_id(external_id, request_options=request_options)
        return _response.data

    async def update_plan_by_external_id(
        self,
        external_id_: str,
        *,
        name: typing.Optional[str] = OMIT,
        external_id: typing.Optional[str] = OMIT,
        supported_currencies: typing.Optional[typing.Sequence[str]] = OMIT,
        is_default: typing.Optional[bool] = OMIT,
        status: typing.Optional[UpdatePlanRequestStatus] = OMIT,
        attributes: typing.Optional[typing.Sequence[PlanAttributeInput]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Plan:
        """
        Update a plan by your external plan ID. If attributes are provided, they replace the plan's existing attributes. Set status to archive or restore the plan.

        Parameters
        ----------
        external_id_ : str

        name : typing.Optional[str]

        external_id : typing.Optional[str]

        supported_currencies : typing.Optional[typing.Sequence[str]]

        is_default : typing.Optional[bool]

        status : typing.Optional[UpdatePlanRequestStatus]
            Set to `archived` to archive this plan, or `active` to restore it.

        attributes : typing.Optional[typing.Sequence[PlanAttributeInput]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Plan
            200

        Examples
        --------
        import asyncio

        from paid import AsyncPaid

        client = AsyncPaid(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.plans.update_plan_by_external_id(
                external_id_="externalId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_plan_by_external_id(
            external_id_,
            name=name,
            external_id=external_id,
            supported_currencies=supported_currencies,
            is_default=is_default,
            status=status,
            attributes=attributes,
            request_options=request_options,
        )
        return _response.data
