# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.customer import Customer
from ..types.customer_billing_address import CustomerBillingAddress
from ..types.customer_creation_state import CustomerCreationState
from ..types.customer_list_response import CustomerListResponse
from ..types.empty_response import EmptyResponse
from .raw_client import AsyncRawCustomersClient, RawCustomersClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class CustomersClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawCustomersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawCustomersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawCustomersClient
        """
        return self._raw_client

    def list_customers(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CustomerListResponse:
        """
        Get a list of customers for the organization

        Parameters
        ----------
        limit : typing.Optional[int]

        offset : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CustomerListResponse
            200

        Examples
        --------
        from paid import Paid

        client = Paid(
            token="YOUR_TOKEN",
        )
        client.customers.list_customers()
        """
        _response = self._raw_client.list_customers(limit=limit, offset=offset, request_options=request_options)
        return _response.data

    def create_a_new_customer(
        self,
        *,
        name: str,
        legal_name: typing.Optional[str] = OMIT,
        email: typing.Optional[str] = OMIT,
        phone: typing.Optional[str] = OMIT,
        website: typing.Optional[str] = OMIT,
        external_id: typing.Optional[str] = OMIT,
        billing_address: typing.Optional[CustomerBillingAddress] = OMIT,
        creation_state: typing.Optional[CustomerCreationState] = OMIT,
        vat_number: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Customer:
        """
        Creates a new customer for the organization

        Parameters
        ----------
        name : str

        legal_name : typing.Optional[str]

        email : typing.Optional[str]

        phone : typing.Optional[str]

        website : typing.Optional[str]

        external_id : typing.Optional[str]

        billing_address : typing.Optional[CustomerBillingAddress]

        creation_state : typing.Optional[CustomerCreationState]

        vat_number : typing.Optional[str]

        metadata : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Customer
            201

        Examples
        --------
        from paid import Paid

        client = Paid(
            token="YOUR_TOKEN",
        )
        client.customers.create_a_new_customer(
            name="name",
        )
        """
        _response = self._raw_client.create_a_new_customer(
            name=name,
            legal_name=legal_name,
            email=email,
            phone=phone,
            website=website,
            external_id=external_id,
            billing_address=billing_address,
            creation_state=creation_state,
            vat_number=vat_number,
            metadata=metadata,
            request_options=request_options,
        )
        return _response.data

    def get_customer(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Customer:
        """
        Get a customer by its ID

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Customer
            200

        Examples
        --------
        from paid import Paid

        client = Paid(
            token="YOUR_TOKEN",
        )
        client.customers.get_customer(
            id="id",
        )
        """
        _response = self._raw_client.get_customer(id, request_options=request_options)
        return _response.data

    def update_customer(
        self,
        id: str,
        *,
        name: typing.Optional[str] = OMIT,
        legal_name: typing.Optional[str] = OMIT,
        email: typing.Optional[str] = OMIT,
        phone: typing.Optional[str] = OMIT,
        website: typing.Optional[str] = OMIT,
        external_id: typing.Optional[str] = OMIT,
        billing_address: typing.Optional[CustomerBillingAddress] = OMIT,
        creation_state: typing.Optional[CustomerCreationState] = OMIT,
        churn_date: typing.Optional[dt.datetime] = OMIT,
        vat_number: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Customer:
        """
        Update a customer by its ID

        Parameters
        ----------
        id : str

        name : typing.Optional[str]

        legal_name : typing.Optional[str]

        email : typing.Optional[str]

        phone : typing.Optional[str]

        website : typing.Optional[str]

        external_id : typing.Optional[str]

        billing_address : typing.Optional[CustomerBillingAddress]

        creation_state : typing.Optional[CustomerCreationState]

        churn_date : typing.Optional[dt.datetime]

        vat_number : typing.Optional[str]

        metadata : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Customer
            200

        Examples
        --------
        from paid import Paid

        client = Paid(
            token="YOUR_TOKEN",
        )
        client.customers.update_customer(
            id="id",
        )
        """
        _response = self._raw_client.update_customer(
            id,
            name=name,
            legal_name=legal_name,
            email=email,
            phone=phone,
            website=website,
            external_id=external_id,
            billing_address=billing_address,
            creation_state=creation_state,
            churn_date=churn_date,
            vat_number=vat_number,
            metadata=metadata,
            request_options=request_options,
        )
        return _response.data

    def delete_customer(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> EmptyResponse:
        """
        Delete a customer by its ID

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EmptyResponse
            200

        Examples
        --------
        from paid import Paid

        client = Paid(
            token="YOUR_TOKEN",
        )
        client.customers.delete_customer(
            id="id",
        )
        """
        _response = self._raw_client.delete_customer(id, request_options=request_options)
        return _response.data

    def get_customer_by_external_id(
        self, external_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> Customer:
        """
        Get a customer by its externalId

        Parameters
        ----------
        external_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Customer
            200

        Examples
        --------
        from paid import Paid

        client = Paid(
            token="YOUR_TOKEN",
        )
        client.customers.get_customer_by_external_id(
            external_id="externalId",
        )
        """
        _response = self._raw_client.get_customer_by_external_id(external_id, request_options=request_options)
        return _response.data

    def update_customer_by_external_id(
        self,
        external_id_: str,
        *,
        name: typing.Optional[str] = OMIT,
        legal_name: typing.Optional[str] = OMIT,
        email: typing.Optional[str] = OMIT,
        phone: typing.Optional[str] = OMIT,
        website: typing.Optional[str] = OMIT,
        external_id: typing.Optional[str] = OMIT,
        billing_address: typing.Optional[CustomerBillingAddress] = OMIT,
        creation_state: typing.Optional[CustomerCreationState] = OMIT,
        churn_date: typing.Optional[dt.datetime] = OMIT,
        vat_number: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Customer:
        """
        Update a customer by its externalId

        Parameters
        ----------
        external_id_ : str

        name : typing.Optional[str]

        legal_name : typing.Optional[str]

        email : typing.Optional[str]

        phone : typing.Optional[str]

        website : typing.Optional[str]

        external_id : typing.Optional[str]

        billing_address : typing.Optional[CustomerBillingAddress]

        creation_state : typing.Optional[CustomerCreationState]

        churn_date : typing.Optional[dt.datetime]

        vat_number : typing.Optional[str]

        metadata : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Customer
            200

        Examples
        --------
        from paid import Paid

        client = Paid(
            token="YOUR_TOKEN",
        )
        client.customers.update_customer_by_external_id(
            external_id_="externalId",
        )
        """
        _response = self._raw_client.update_customer_by_external_id(
            external_id_,
            name=name,
            legal_name=legal_name,
            email=email,
            phone=phone,
            website=website,
            external_id=external_id,
            billing_address=billing_address,
            creation_state=creation_state,
            churn_date=churn_date,
            vat_number=vat_number,
            metadata=metadata,
            request_options=request_options,
        )
        return _response.data

    def delete_customer_by_external_id(
        self, external_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> EmptyResponse:
        """
        Delete a customer by its externalId

        Parameters
        ----------
        external_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EmptyResponse
            200

        Examples
        --------
        from paid import Paid

        client = Paid(
            token="YOUR_TOKEN",
        )
        client.customers.delete_customer_by_external_id(
            external_id="externalId",
        )
        """
        _response = self._raw_client.delete_customer_by_external_id(external_id, request_options=request_options)
        return _response.data


class AsyncCustomersClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawCustomersClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawCustomersClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawCustomersClient
        """
        return self._raw_client

    async def list_customers(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CustomerListResponse:
        """
        Get a list of customers for the organization

        Parameters
        ----------
        limit : typing.Optional[int]

        offset : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CustomerListResponse
            200

        Examples
        --------
        import asyncio

        from paid import AsyncPaid

        client = AsyncPaid(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.customers.list_customers()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_customers(limit=limit, offset=offset, request_options=request_options)
        return _response.data

    async def create_a_new_customer(
        self,
        *,
        name: str,
        legal_name: typing.Optional[str] = OMIT,
        email: typing.Optional[str] = OMIT,
        phone: typing.Optional[str] = OMIT,
        website: typing.Optional[str] = OMIT,
        external_id: typing.Optional[str] = OMIT,
        billing_address: typing.Optional[CustomerBillingAddress] = OMIT,
        creation_state: typing.Optional[CustomerCreationState] = OMIT,
        vat_number: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Customer:
        """
        Creates a new customer for the organization

        Parameters
        ----------
        name : str

        legal_name : typing.Optional[str]

        email : typing.Optional[str]

        phone : typing.Optional[str]

        website : typing.Optional[str]

        external_id : typing.Optional[str]

        billing_address : typing.Optional[CustomerBillingAddress]

        creation_state : typing.Optional[CustomerCreationState]

        vat_number : typing.Optional[str]

        metadata : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Customer
            201

        Examples
        --------
        import asyncio

        from paid import AsyncPaid

        client = AsyncPaid(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.customers.create_a_new_customer(
                name="name",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_a_new_customer(
            name=name,
            legal_name=legal_name,
            email=email,
            phone=phone,
            website=website,
            external_id=external_id,
            billing_address=billing_address,
            creation_state=creation_state,
            vat_number=vat_number,
            metadata=metadata,
            request_options=request_options,
        )
        return _response.data

    async def get_customer(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Customer:
        """
        Get a customer by its ID

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Customer
            200

        Examples
        --------
        import asyncio

        from paid import AsyncPaid

        client = AsyncPaid(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.customers.get_customer(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_customer(id, request_options=request_options)
        return _response.data

    async def update_customer(
        self,
        id: str,
        *,
        name: typing.Optional[str] = OMIT,
        legal_name: typing.Optional[str] = OMIT,
        email: typing.Optional[str] = OMIT,
        phone: typing.Optional[str] = OMIT,
        website: typing.Optional[str] = OMIT,
        external_id: typing.Optional[str] = OMIT,
        billing_address: typing.Optional[CustomerBillingAddress] = OMIT,
        creation_state: typing.Optional[CustomerCreationState] = OMIT,
        churn_date: typing.Optional[dt.datetime] = OMIT,
        vat_number: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Customer:
        """
        Update a customer by its ID

        Parameters
        ----------
        id : str

        name : typing.Optional[str]

        legal_name : typing.Optional[str]

        email : typing.Optional[str]

        phone : typing.Optional[str]

        website : typing.Optional[str]

        external_id : typing.Optional[str]

        billing_address : typing.Optional[CustomerBillingAddress]

        creation_state : typing.Optional[CustomerCreationState]

        churn_date : typing.Optional[dt.datetime]

        vat_number : typing.Optional[str]

        metadata : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Customer
            200

        Examples
        --------
        import asyncio

        from paid import AsyncPaid

        client = AsyncPaid(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.customers.update_customer(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_customer(
            id,
            name=name,
            legal_name=legal_name,
            email=email,
            phone=phone,
            website=website,
            external_id=external_id,
            billing_address=billing_address,
            creation_state=creation_state,
            churn_date=churn_date,
            vat_number=vat_number,
            metadata=metadata,
            request_options=request_options,
        )
        return _response.data

    async def delete_customer(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> EmptyResponse:
        """
        Delete a customer by its ID

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EmptyResponse
            200

        Examples
        --------
        import asyncio

        from paid import AsyncPaid

        client = AsyncPaid(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.customers.delete_customer(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_customer(id, request_options=request_options)
        return _response.data

    async def get_customer_by_external_id(
        self, external_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> Customer:
        """
        Get a customer by its externalId

        Parameters
        ----------
        external_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Customer
            200

        Examples
        --------
        import asyncio

        from paid import AsyncPaid

        client = AsyncPaid(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.customers.get_customer_by_external_id(
                external_id="externalId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_customer_by_external_id(external_id, request_options=request_options)
        return _response.data

    async def update_customer_by_external_id(
        self,
        external_id_: str,
        *,
        name: typing.Optional[str] = OMIT,
        legal_name: typing.Optional[str] = OMIT,
        email: typing.Optional[str] = OMIT,
        phone: typing.Optional[str] = OMIT,
        website: typing.Optional[str] = OMIT,
        external_id: typing.Optional[str] = OMIT,
        billing_address: typing.Optional[CustomerBillingAddress] = OMIT,
        creation_state: typing.Optional[CustomerCreationState] = OMIT,
        churn_date: typing.Optional[dt.datetime] = OMIT,
        vat_number: typing.Optional[str] = OMIT,
        metadata: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Customer:
        """
        Update a customer by its externalId

        Parameters
        ----------
        external_id_ : str

        name : typing.Optional[str]

        legal_name : typing.Optional[str]

        email : typing.Optional[str]

        phone : typing.Optional[str]

        website : typing.Optional[str]

        external_id : typing.Optional[str]

        billing_address : typing.Optional[CustomerBillingAddress]

        creation_state : typing.Optional[CustomerCreationState]

        churn_date : typing.Optional[dt.datetime]

        vat_number : typing.Optional[str]

        metadata : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Customer
            200

        Examples
        --------
        import asyncio

        from paid import AsyncPaid

        client = AsyncPaid(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.customers.update_customer_by_external_id(
                external_id_="externalId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_customer_by_external_id(
            external_id_,
            name=name,
            legal_name=legal_name,
            email=email,
            phone=phone,
            website=website,
            external_id=external_id,
            billing_address=billing_address,
            creation_state=creation_state,
            churn_date=churn_date,
            vat_number=vat_number,
            metadata=metadata,
            request_options=request_options,
        )
        return _response.data

    async def delete_customer_by_external_id(
        self, external_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> EmptyResponse:
        """
        Delete a customer by its externalId

        Parameters
        ----------
        external_id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        EmptyResponse
            200

        Examples
        --------
        import asyncio

        from paid import AsyncPaid

        client = AsyncPaid(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.customers.delete_customer_by_external_id(
                external_id="externalId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_customer_by_external_id(external_id, request_options=request_options)
        return _response.data
