# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.invoice import Invoice
from ..types.invoice_lines_response import InvoiceLinesResponse
from ..types.invoice_list_response import InvoiceListResponse
from .raw_client import AsyncRawInvoicesClient, RawInvoicesClient
from .types.list_invoices_request_payment_status import ListInvoicesRequestPaymentStatus
from .types.list_invoices_request_status import ListInvoicesRequestStatus

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class InvoicesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawInvoicesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawInvoicesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawInvoicesClient
        """
        return self._raw_client

    def list_invoices(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        customer_id: typing.Optional[str] = None,
        external_customer_id: typing.Optional[str] = None,
        order_id: typing.Optional[str] = None,
        status: typing.Optional[ListInvoicesRequestStatus] = None,
        payment_status: typing.Optional[ListInvoicesRequestPaymentStatus] = None,
        issue_date_from: typing.Optional[str] = None,
        issue_date_to: typing.Optional[str] = None,
        due_date_from: typing.Optional[str] = None,
        due_date_to: typing.Optional[str] = None,
        display_number: typing.Optional[str] = None,
        purchase_order_reference: typing.Optional[str] = None,
        currency: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> InvoiceListResponse:
        """
        Get a list of invoices for the organization

        Parameters
        ----------
        limit : typing.Optional[int]

        offset : typing.Optional[int]

        customer_id : typing.Optional[str]
            Filter by customer ID.

        external_customer_id : typing.Optional[str]
            Filter by customer external ID.

        order_id : typing.Optional[str]
            Filter by the order this invoice was generated from.

        status : typing.Optional[ListInvoicesRequestStatus]
            Filter by invoice status.

        payment_status : typing.Optional[ListInvoicesRequestPaymentStatus]
            Filter by payment status.

        issue_date_from : typing.Optional[str]
            Only invoices whose issue date is on or after this date. Accepts an ISO 8601 date or date-time. Date-only values (e.g. 2026-06-30) are treated as UTC; date-times without an explicit timezone offset are ambiguous, so include one (e.g. 2026-06-30T00:00:00-05:00) when precision matters.

        issue_date_to : typing.Optional[str]
            Only invoices whose issue date is on or before this date. Accepts an ISO 8601 date or date-time. Date-only values (e.g. 2026-06-30) are treated as UTC; date-times without an explicit timezone offset are ambiguous, so include one (e.g. 2026-06-30T00:00:00-05:00) when precision matters.

        due_date_from : typing.Optional[str]
            Only invoices whose due date is on or after this date. Invoices without a due date are not matched. Accepts an ISO 8601 date or date-time. Date-only values (e.g. 2026-06-30) are treated as UTC; date-times without an explicit timezone offset are ambiguous, so include one (e.g. 2026-06-30T00:00:00-05:00) when precision matters.

        due_date_to : typing.Optional[str]
            Only invoices whose due date is on or before this date. Invoices without a due date are not matched. Accepts an ISO 8601 date or date-time. Date-only values (e.g. 2026-06-30) are treated as UTC; date-times without an explicit timezone offset are ambiguous, so include one (e.g. 2026-06-30T00:00:00-05:00) when precision matters.

        display_number : typing.Optional[str]
            Filter by the invoice number shown on the invoice, whether draft or posted (exact match).

        purchase_order_reference : typing.Optional[str]
            Filter by purchase order reference (exact match, whitespace-sensitive).

        currency : typing.Optional[str]
            Filter by invoice currency code (case-insensitive, e.g. USD).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InvoiceListResponse
            200

        Examples
        --------
        from paid import Paid

        client = Paid(
            token="YOUR_TOKEN",
        )
        client.invoices.list_invoices()
        """
        _response = self._raw_client.list_invoices(
            limit=limit,
            offset=offset,
            customer_id=customer_id,
            external_customer_id=external_customer_id,
            order_id=order_id,
            status=status,
            payment_status=payment_status,
            issue_date_from=issue_date_from,
            issue_date_to=issue_date_to,
            due_date_from=due_date_from,
            due_date_to=due_date_to,
            display_number=display_number,
            purchase_order_reference=purchase_order_reference,
            currency=currency,
            request_options=request_options,
        )
        return _response.data

    def get_invoice_by_id(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Invoice:
        """
        Get an invoice by ID

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Invoice
            200

        Examples
        --------
        from paid import Paid

        client = Paid(
            token="YOUR_TOKEN",
        )
        client.invoices.get_invoice_by_id(
            id="id",
        )
        """
        _response = self._raw_client.get_invoice_by_id(id, request_options=request_options)
        return _response.data

    def update_invoice_by_id(
        self,
        id: str,
        *,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Invoice:
        """
        Update an invoice by ID

        Parameters
        ----------
        id : str

        metadata : typing.Optional[typing.Dict[str, typing.Any]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Invoice
            200

        Examples
        --------
        from paid import Paid

        client = Paid(
            token="YOUR_TOKEN",
        )
        client.invoices.update_invoice_by_id(
            id="id",
        )
        """
        _response = self._raw_client.update_invoice_by_id(id, metadata=metadata, request_options=request_options)
        return _response.data

    def get_invoice_lines(
        self,
        id: str,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> InvoiceLinesResponse:
        """
        Get the invoice lines for an invoice by ID

        Parameters
        ----------
        id : str

        limit : typing.Optional[int]

        offset : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InvoiceLinesResponse
            200

        Examples
        --------
        from paid import Paid

        client = Paid(
            token="YOUR_TOKEN",
        )
        client.invoices.get_invoice_lines(
            id="id",
        )
        """
        _response = self._raw_client.get_invoice_lines(id, limit=limit, offset=offset, request_options=request_options)
        return _response.data


class AsyncInvoicesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawInvoicesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawInvoicesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawInvoicesClient
        """
        return self._raw_client

    async def list_invoices(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        customer_id: typing.Optional[str] = None,
        external_customer_id: typing.Optional[str] = None,
        order_id: typing.Optional[str] = None,
        status: typing.Optional[ListInvoicesRequestStatus] = None,
        payment_status: typing.Optional[ListInvoicesRequestPaymentStatus] = None,
        issue_date_from: typing.Optional[str] = None,
        issue_date_to: typing.Optional[str] = None,
        due_date_from: typing.Optional[str] = None,
        due_date_to: typing.Optional[str] = None,
        display_number: typing.Optional[str] = None,
        purchase_order_reference: typing.Optional[str] = None,
        currency: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> InvoiceListResponse:
        """
        Get a list of invoices for the organization

        Parameters
        ----------
        limit : typing.Optional[int]

        offset : typing.Optional[int]

        customer_id : typing.Optional[str]
            Filter by customer ID.

        external_customer_id : typing.Optional[str]
            Filter by customer external ID.

        order_id : typing.Optional[str]
            Filter by the order this invoice was generated from.

        status : typing.Optional[ListInvoicesRequestStatus]
            Filter by invoice status.

        payment_status : typing.Optional[ListInvoicesRequestPaymentStatus]
            Filter by payment status.

        issue_date_from : typing.Optional[str]
            Only invoices whose issue date is on or after this date. Accepts an ISO 8601 date or date-time. Date-only values (e.g. 2026-06-30) are treated as UTC; date-times without an explicit timezone offset are ambiguous, so include one (e.g. 2026-06-30T00:00:00-05:00) when precision matters.

        issue_date_to : typing.Optional[str]
            Only invoices whose issue date is on or before this date. Accepts an ISO 8601 date or date-time. Date-only values (e.g. 2026-06-30) are treated as UTC; date-times without an explicit timezone offset are ambiguous, so include one (e.g. 2026-06-30T00:00:00-05:00) when precision matters.

        due_date_from : typing.Optional[str]
            Only invoices whose due date is on or after this date. Invoices without a due date are not matched. Accepts an ISO 8601 date or date-time. Date-only values (e.g. 2026-06-30) are treated as UTC; date-times without an explicit timezone offset are ambiguous, so include one (e.g. 2026-06-30T00:00:00-05:00) when precision matters.

        due_date_to : typing.Optional[str]
            Only invoices whose due date is on or before this date. Invoices without a due date are not matched. Accepts an ISO 8601 date or date-time. Date-only values (e.g. 2026-06-30) are treated as UTC; date-times without an explicit timezone offset are ambiguous, so include one (e.g. 2026-06-30T00:00:00-05:00) when precision matters.

        display_number : typing.Optional[str]
            Filter by the invoice number shown on the invoice, whether draft or posted (exact match).

        purchase_order_reference : typing.Optional[str]
            Filter by purchase order reference (exact match, whitespace-sensitive).

        currency : typing.Optional[str]
            Filter by invoice currency code (case-insensitive, e.g. USD).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InvoiceListResponse
            200

        Examples
        --------
        import asyncio

        from paid import AsyncPaid

        client = AsyncPaid(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.invoices.list_invoices()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_invoices(
            limit=limit,
            offset=offset,
            customer_id=customer_id,
            external_customer_id=external_customer_id,
            order_id=order_id,
            status=status,
            payment_status=payment_status,
            issue_date_from=issue_date_from,
            issue_date_to=issue_date_to,
            due_date_from=due_date_from,
            due_date_to=due_date_to,
            display_number=display_number,
            purchase_order_reference=purchase_order_reference,
            currency=currency,
            request_options=request_options,
        )
        return _response.data

    async def get_invoice_by_id(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> Invoice:
        """
        Get an invoice by ID

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Invoice
            200

        Examples
        --------
        import asyncio

        from paid import AsyncPaid

        client = AsyncPaid(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.invoices.get_invoice_by_id(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_invoice_by_id(id, request_options=request_options)
        return _response.data

    async def update_invoice_by_id(
        self,
        id: str,
        *,
        metadata: typing.Optional[typing.Dict[str, typing.Any]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> Invoice:
        """
        Update an invoice by ID

        Parameters
        ----------
        id : str

        metadata : typing.Optional[typing.Dict[str, typing.Any]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        Invoice
            200

        Examples
        --------
        import asyncio

        from paid import AsyncPaid

        client = AsyncPaid(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.invoices.update_invoice_by_id(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_invoice_by_id(id, metadata=metadata, request_options=request_options)
        return _response.data

    async def get_invoice_lines(
        self,
        id: str,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> InvoiceLinesResponse:
        """
        Get the invoice lines for an invoice by ID

        Parameters
        ----------
        id : str

        limit : typing.Optional[int]

        offset : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        InvoiceLinesResponse
            200

        Examples
        --------
        import asyncio

        from paid import AsyncPaid

        client = AsyncPaid(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.invoices.get_invoice_lines(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_invoice_lines(
            id, limit=limit, offset=offset, request_options=request_options
        )
        return _response.data
