# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawInvoicesClient, RawInvoicesClient
from .types.get_invoices_id_lines_response import GetInvoicesIdLinesResponse
from .types.get_invoices_id_response import GetInvoicesIdResponse
from .types.get_invoices_response import GetInvoicesResponse
from .types.put_invoices_id_response import PutInvoicesIdResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class InvoicesClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawInvoicesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawInvoicesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawInvoicesClient
        """
        return self._raw_client

    def list_invoices(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetInvoicesResponse:
        """
        Get a list of invoices for the organization

        Parameters
        ----------
        limit : typing.Optional[int]

        offset : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetInvoicesResponse
            200

        Examples
        --------
        from paid import Paid

        client = Paid(
            token="YOUR_TOKEN",
        )
        client.invoices.list_invoices()
        """
        _response = self._raw_client.list_invoices(limit=limit, offset=offset, request_options=request_options)
        return _response.data

    def get_invoice(self, id: str, *, request_options: typing.Optional[RequestOptions] = None) -> GetInvoicesIdResponse:
        """
        Get an invoice by its ID

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetInvoicesIdResponse
            200

        Examples
        --------
        from paid import Paid

        client = Paid(
            token="YOUR_TOKEN",
        )
        client.invoices.get_invoice(
            id="id",
        )
        """
        _response = self._raw_client.get_invoice(id, request_options=request_options)
        return _response.data

    def update_invoice(
        self,
        id: str,
        *,
        metadata: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PutInvoicesIdResponse:
        """
        Update an invoice by its ID (limited fields)

        Parameters
        ----------
        id : str

        metadata : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PutInvoicesIdResponse
            200

        Examples
        --------
        from paid import Paid

        client = Paid(
            token="YOUR_TOKEN",
        )
        client.invoices.update_invoice(
            id="id",
        )
        """
        _response = self._raw_client.update_invoice(id, metadata=metadata, request_options=request_options)
        return _response.data

    def get_invoice_lines(
        self,
        id: str,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetInvoicesIdLinesResponse:
        """
        Get the invoice lines for an invoice by its ID

        Parameters
        ----------
        id : str

        limit : typing.Optional[int]

        offset : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetInvoicesIdLinesResponse
            200

        Examples
        --------
        from paid import Paid

        client = Paid(
            token="YOUR_TOKEN",
        )
        client.invoices.get_invoice_lines(
            id="id",
        )
        """
        _response = self._raw_client.get_invoice_lines(id, limit=limit, offset=offset, request_options=request_options)
        return _response.data


class AsyncInvoicesClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawInvoicesClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawInvoicesClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawInvoicesClient
        """
        return self._raw_client

    async def list_invoices(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetInvoicesResponse:
        """
        Get a list of invoices for the organization

        Parameters
        ----------
        limit : typing.Optional[int]

        offset : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetInvoicesResponse
            200

        Examples
        --------
        import asyncio

        from paid import AsyncPaid

        client = AsyncPaid(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.invoices.list_invoices()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_invoices(limit=limit, offset=offset, request_options=request_options)
        return _response.data

    async def get_invoice(
        self, id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> GetInvoicesIdResponse:
        """
        Get an invoice by its ID

        Parameters
        ----------
        id : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetInvoicesIdResponse
            200

        Examples
        --------
        import asyncio

        from paid import AsyncPaid

        client = AsyncPaid(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.invoices.get_invoice(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_invoice(id, request_options=request_options)
        return _response.data

    async def update_invoice(
        self,
        id: str,
        *,
        metadata: typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PutInvoicesIdResponse:
        """
        Update an invoice by its ID (limited fields)

        Parameters
        ----------
        id : str

        metadata : typing.Optional[typing.Dict[str, typing.Optional[typing.Any]]]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PutInvoicesIdResponse
            200

        Examples
        --------
        import asyncio

        from paid import AsyncPaid

        client = AsyncPaid(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.invoices.update_invoice(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_invoice(id, metadata=metadata, request_options=request_options)
        return _response.data

    async def get_invoice_lines(
        self,
        id: str,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> GetInvoicesIdLinesResponse:
        """
        Get the invoice lines for an invoice by its ID

        Parameters
        ----------
        id : str

        limit : typing.Optional[int]

        offset : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        GetInvoicesIdLinesResponse
            200

        Examples
        --------
        import asyncio

        from paid import AsyncPaid

        client = AsyncPaid(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.invoices.get_invoice_lines(
                id="id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_invoice_lines(
            id, limit=limit, offset=offset, request_options=request_options
        )
        return _response.data
