# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.value_metric_detail import ValueMetricDetail
from ..types.value_metric_formula import ValueMetricFormula
from ..types.value_metric_list_response import ValueMetricListResponse
from ..types.value_metric_monetary_conversion import ValueMetricMonetaryConversion
from ..types.value_metric_signal_binding import ValueMetricSignalBinding
from ..types.value_metric_unit import ValueMetricUnit
from ..types.value_metric_variable_edit import ValueMetricVariableEdit
from ..types.value_metric_write_ack import ValueMetricWriteAck
from .raw_client import AsyncRawValueMetricsClient, RawValueMetricsClient
from .types.create_value_metric_request_category import CreateValueMetricRequestCategory
from .types.create_value_metric_request_sources_item import CreateValueMetricRequestSourcesItem
from .types.update_value_metric_request_category import UpdateValueMetricRequestCategory
from .types.update_value_metric_request_sources_item import UpdateValueMetricRequestSourcesItem

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ValueMetricsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawValueMetricsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawValueMetricsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawValueMetricsClient
        """
        return self._raw_client

    def list_value_metrics(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        include_archived: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ValueMetricListResponse:
        """
        Returns the value metrics in the current value model, without their formulas. Archived metrics are hidden unless includeArchived is true.

        Parameters
        ----------
        limit : typing.Optional[int]

        offset : typing.Optional[int]

        include_archived : typing.Optional[bool]
            Whether to include archived metrics in the response. Defaults to false.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ValueMetricListResponse
            200

        Examples
        --------
        from paid import Paid

        client = Paid(
            token="YOUR_TOKEN",
        )
        client.value_metrics.list_value_metrics()
        """
        _response = self._raw_client.list_value_metrics(
            limit=limit, offset=offset, include_archived=include_archived, request_options=request_options
        )
        return _response.data

    def create_value_metric(
        self,
        *,
        name: str,
        unit: ValueMetricUnit,
        formula: ValueMetricFormula,
        signal: ValueMetricSignalBinding,
        slug: typing.Optional[str] = OMIT,
        monetary_conversion: typing.Optional[ValueMetricMonetaryConversion] = OMIT,
        category: typing.Optional[CreateValueMetricRequestCategory] = OMIT,
        description: typing.Optional[str] = OMIT,
        long_description: typing.Optional[str] = OMIT,
        sources: typing.Optional[typing.Sequence[CreateValueMetricRequestSourcesItem]] = OMIT,
        expected_active_version: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ValueMetricWriteAck:
        """
        Adds one value metric — its unit, formula, signal binding and optional monetary conversion — to the value model. The signal must already exist: an event name your organization has sent, or one referenced by usage pricing on an active product. Publishes a new value model version and recalculates delivered value for historical signals.

        Parameters
        ----------
        name : str
            Customer-facing metric name.

        unit : ValueMetricUnit

        formula : ValueMetricFormula

        signal : ValueMetricSignalBinding

        slug : typing.Optional[str]
            Stable identifier. Derived from the name when omitted.

        monetary_conversion : typing.Optional[ValueMetricMonetaryConversion]

        category : typing.Optional[CreateValueMetricRequestCategory]
            Classification: hve = human value equivalent, time = time saved, cost = cost savings, revenue = revenue generated, risk = risk avoided.

        description : typing.Optional[str]
            Short customer-facing copy shown on value receipts.

        long_description : typing.Optional[str]

        sources : typing.Optional[typing.Sequence[CreateValueMetricRequestSourcesItem]]
            Up to 3 customer-facing citations backing this metric.

        expected_active_version : typing.Optional[int]
            Optimistic concurrency guard. When supplied and it does not match the live active version, the request fails with 409 instead of overwriting a concurrent change.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ValueMetricWriteAck
            201

        Examples
        --------
        from paid import (
            Paid,
            ValueMetricFormula,
            ValueMetricFormulaVariable,
            ValueMetricSignalBinding,
            ValueMetricUnit,
        )

        client = Paid(
            token="YOUR_TOKEN",
        )
        client.value_metrics.create_value_metric(
            name="Time saved",
            unit=ValueMetricUnit(
                type="monetary",
            ),
            formula=ValueMetricFormula(
                expression="minutes_saved / 60",
                variables=[
                    ValueMetricFormulaVariable(
                        id="id",
                        label="label",
                    )
                ],
            ),
            signal=ValueMetricSignalBinding(
                event_name="ticket_resolved",
            ),
        )
        """
        _response = self._raw_client.create_value_metric(
            name=name,
            unit=unit,
            formula=formula,
            signal=signal,
            slug=slug,
            monetary_conversion=monetary_conversion,
            category=category,
            description=description,
            long_description=long_description,
            sources=sources,
            expected_active_version=expected_active_version,
            request_options=request_options,
        )
        return _response.data

    def get_value_metric(
        self, slug: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ValueMetricDetail:
        """
        Returns one value metric with its formula, signal binding and monetary conversion joined together. Call getCurrentValueModel if you need the active version number to guard a follow-up write.

        Parameters
        ----------
        slug : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ValueMetricDetail
            200

        Examples
        --------
        from paid import Paid

        client = Paid(
            token="YOUR_TOKEN",
        )
        client.value_metrics.get_value_metric(
            slug="slug",
        )
        """
        _response = self._raw_client.get_value_metric(slug, request_options=request_options)
        return _response.data

    def archive_value_metric(
        self,
        slug: str,
        *,
        expected_active_version: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ValueMetricWriteAck:
        """
        Marks a value metric archived so it stops appearing in listValueMetrics. Its formula and signal bindings are deliberately kept, so historical delivered value and sealed value receipts still resolve — which also means an archived metric's signals continue to be ingested and can still surface on value receipts. Removing it from receipts entirely requires deleting its signal bindings. Restore it with updateValueMetric and archivedAt null.

        Parameters
        ----------
        slug : str

        expected_active_version : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ValueMetricWriteAck
            200

        Examples
        --------
        from paid import Paid

        client = Paid(
            token="YOUR_TOKEN",
        )
        client.value_metrics.archive_value_metric(
            slug="slug",
        )
        """
        _response = self._raw_client.archive_value_metric(
            slug, expected_active_version=expected_active_version, request_options=request_options
        )
        return _response.data

    def update_value_metric(
        self,
        slug: str,
        *,
        name: typing.Optional[str] = OMIT,
        unit: typing.Optional[ValueMetricUnit] = OMIT,
        monetary_conversion: typing.Optional[ValueMetricMonetaryConversion] = OMIT,
        variables: typing.Optional[typing.Dict[str, ValueMetricVariableEdit]] = OMIT,
        archived_at: typing.Optional[dt.datetime] = OMIT,
        category: typing.Optional[UpdateValueMetricRequestCategory] = OMIT,
        description: typing.Optional[str] = OMIT,
        long_description: typing.Optional[str] = OMIT,
        sources: typing.Optional[typing.Sequence[UpdateValueMetricRequestSourcesItem]] = OMIT,
        expected_active_version: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ValueMetricWriteAck:
        """
        Changes one value metric. Omitted fields are left alone. You can change its name, category, unit, customer-facing copy, sources, monetary rate, archive state, and the value, label or display format of any variable its formula declares. The formula expression and the signal it is bound to cannot be changed — recreate the metric, or use the whole value-model upload. Publishes a new value model version.

        Parameters
        ----------
        slug : str

        name : typing.Optional[str]

        unit : typing.Optional[ValueMetricUnit]

        monetary_conversion : typing.Optional[ValueMetricMonetaryConversion]

        variables : typing.Optional[typing.Dict[str, ValueMetricVariableEdit]]
            Per-variable edits, keyed by the variable id the formula declares. Merged: a variable you do not name is untouched. Naming one the formula does not declare is an error rather than a no-op.

        archived_at : typing.Optional[dt.datetime]
            Set null to restore an archived metric.

        category : typing.Optional[UpdateValueMetricRequestCategory]
            Classification: hve = human value equivalent, time = time saved, cost = cost savings, revenue = revenue generated, risk = risk avoided.

        description : typing.Optional[str]
            Short customer-facing copy shown on value receipts.

        long_description : typing.Optional[str]

        sources : typing.Optional[typing.Sequence[UpdateValueMetricRequestSourcesItem]]
            Up to 3 customer-facing citations backing this metric.

        expected_active_version : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ValueMetricWriteAck
            200

        Examples
        --------
        from paid import Paid

        client = Paid(
            token="YOUR_TOKEN",
        )
        client.value_metrics.update_value_metric(
            slug="slug",
        )
        """
        _response = self._raw_client.update_value_metric(
            slug,
            name=name,
            unit=unit,
            monetary_conversion=monetary_conversion,
            variables=variables,
            archived_at=archived_at,
            category=category,
            description=description,
            long_description=long_description,
            sources=sources,
            expected_active_version=expected_active_version,
            request_options=request_options,
        )
        return _response.data


class AsyncValueMetricsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawValueMetricsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawValueMetricsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawValueMetricsClient
        """
        return self._raw_client

    async def list_value_metrics(
        self,
        *,
        limit: typing.Optional[int] = None,
        offset: typing.Optional[int] = None,
        include_archived: typing.Optional[bool] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ValueMetricListResponse:
        """
        Returns the value metrics in the current value model, without their formulas. Archived metrics are hidden unless includeArchived is true.

        Parameters
        ----------
        limit : typing.Optional[int]

        offset : typing.Optional[int]

        include_archived : typing.Optional[bool]
            Whether to include archived metrics in the response. Defaults to false.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ValueMetricListResponse
            200

        Examples
        --------
        import asyncio

        from paid import AsyncPaid

        client = AsyncPaid(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.value_metrics.list_value_metrics()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_value_metrics(
            limit=limit, offset=offset, include_archived=include_archived, request_options=request_options
        )
        return _response.data

    async def create_value_metric(
        self,
        *,
        name: str,
        unit: ValueMetricUnit,
        formula: ValueMetricFormula,
        signal: ValueMetricSignalBinding,
        slug: typing.Optional[str] = OMIT,
        monetary_conversion: typing.Optional[ValueMetricMonetaryConversion] = OMIT,
        category: typing.Optional[CreateValueMetricRequestCategory] = OMIT,
        description: typing.Optional[str] = OMIT,
        long_description: typing.Optional[str] = OMIT,
        sources: typing.Optional[typing.Sequence[CreateValueMetricRequestSourcesItem]] = OMIT,
        expected_active_version: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ValueMetricWriteAck:
        """
        Adds one value metric — its unit, formula, signal binding and optional monetary conversion — to the value model. The signal must already exist: an event name your organization has sent, or one referenced by usage pricing on an active product. Publishes a new value model version and recalculates delivered value for historical signals.

        Parameters
        ----------
        name : str
            Customer-facing metric name.

        unit : ValueMetricUnit

        formula : ValueMetricFormula

        signal : ValueMetricSignalBinding

        slug : typing.Optional[str]
            Stable identifier. Derived from the name when omitted.

        monetary_conversion : typing.Optional[ValueMetricMonetaryConversion]

        category : typing.Optional[CreateValueMetricRequestCategory]
            Classification: hve = human value equivalent, time = time saved, cost = cost savings, revenue = revenue generated, risk = risk avoided.

        description : typing.Optional[str]
            Short customer-facing copy shown on value receipts.

        long_description : typing.Optional[str]

        sources : typing.Optional[typing.Sequence[CreateValueMetricRequestSourcesItem]]
            Up to 3 customer-facing citations backing this metric.

        expected_active_version : typing.Optional[int]
            Optimistic concurrency guard. When supplied and it does not match the live active version, the request fails with 409 instead of overwriting a concurrent change.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ValueMetricWriteAck
            201

        Examples
        --------
        import asyncio

        from paid import (
            AsyncPaid,
            ValueMetricFormula,
            ValueMetricFormulaVariable,
            ValueMetricSignalBinding,
            ValueMetricUnit,
        )

        client = AsyncPaid(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.value_metrics.create_value_metric(
                name="Time saved",
                unit=ValueMetricUnit(
                    type="monetary",
                ),
                formula=ValueMetricFormula(
                    expression="minutes_saved / 60",
                    variables=[
                        ValueMetricFormulaVariable(
                            id="id",
                            label="label",
                        )
                    ],
                ),
                signal=ValueMetricSignalBinding(
                    event_name="ticket_resolved",
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_value_metric(
            name=name,
            unit=unit,
            formula=formula,
            signal=signal,
            slug=slug,
            monetary_conversion=monetary_conversion,
            category=category,
            description=description,
            long_description=long_description,
            sources=sources,
            expected_active_version=expected_active_version,
            request_options=request_options,
        )
        return _response.data

    async def get_value_metric(
        self, slug: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> ValueMetricDetail:
        """
        Returns one value metric with its formula, signal binding and monetary conversion joined together. Call getCurrentValueModel if you need the active version number to guard a follow-up write.

        Parameters
        ----------
        slug : str

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ValueMetricDetail
            200

        Examples
        --------
        import asyncio

        from paid import AsyncPaid

        client = AsyncPaid(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.value_metrics.get_value_metric(
                slug="slug",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_value_metric(slug, request_options=request_options)
        return _response.data

    async def archive_value_metric(
        self,
        slug: str,
        *,
        expected_active_version: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ValueMetricWriteAck:
        """
        Marks a value metric archived so it stops appearing in listValueMetrics. Its formula and signal bindings are deliberately kept, so historical delivered value and sealed value receipts still resolve — which also means an archived metric's signals continue to be ingested and can still surface on value receipts. Removing it from receipts entirely requires deleting its signal bindings. Restore it with updateValueMetric and archivedAt null.

        Parameters
        ----------
        slug : str

        expected_active_version : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ValueMetricWriteAck
            200

        Examples
        --------
        import asyncio

        from paid import AsyncPaid

        client = AsyncPaid(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.value_metrics.archive_value_metric(
                slug="slug",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.archive_value_metric(
            slug, expected_active_version=expected_active_version, request_options=request_options
        )
        return _response.data

    async def update_value_metric(
        self,
        slug: str,
        *,
        name: typing.Optional[str] = OMIT,
        unit: typing.Optional[ValueMetricUnit] = OMIT,
        monetary_conversion: typing.Optional[ValueMetricMonetaryConversion] = OMIT,
        variables: typing.Optional[typing.Dict[str, ValueMetricVariableEdit]] = OMIT,
        archived_at: typing.Optional[dt.datetime] = OMIT,
        category: typing.Optional[UpdateValueMetricRequestCategory] = OMIT,
        description: typing.Optional[str] = OMIT,
        long_description: typing.Optional[str] = OMIT,
        sources: typing.Optional[typing.Sequence[UpdateValueMetricRequestSourcesItem]] = OMIT,
        expected_active_version: typing.Optional[int] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ValueMetricWriteAck:
        """
        Changes one value metric. Omitted fields are left alone. You can change its name, category, unit, customer-facing copy, sources, monetary rate, archive state, and the value, label or display format of any variable its formula declares. The formula expression and the signal it is bound to cannot be changed — recreate the metric, or use the whole value-model upload. Publishes a new value model version.

        Parameters
        ----------
        slug : str

        name : typing.Optional[str]

        unit : typing.Optional[ValueMetricUnit]

        monetary_conversion : typing.Optional[ValueMetricMonetaryConversion]

        variables : typing.Optional[typing.Dict[str, ValueMetricVariableEdit]]
            Per-variable edits, keyed by the variable id the formula declares. Merged: a variable you do not name is untouched. Naming one the formula does not declare is an error rather than a no-op.

        archived_at : typing.Optional[dt.datetime]
            Set null to restore an archived metric.

        category : typing.Optional[UpdateValueMetricRequestCategory]
            Classification: hve = human value equivalent, time = time saved, cost = cost savings, revenue = revenue generated, risk = risk avoided.

        description : typing.Optional[str]
            Short customer-facing copy shown on value receipts.

        long_description : typing.Optional[str]

        sources : typing.Optional[typing.Sequence[UpdateValueMetricRequestSourcesItem]]
            Up to 3 customer-facing citations backing this metric.

        expected_active_version : typing.Optional[int]

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ValueMetricWriteAck
            200

        Examples
        --------
        import asyncio

        from paid import AsyncPaid

        client = AsyncPaid(
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.value_metrics.update_value_metric(
                slug="slug",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.update_value_metric(
            slug,
            name=name,
            unit=unit,
            monetary_conversion=monetary_conversion,
            variables=variables,
            archived_at=archived_at,
            category=category,
            description=description,
            long_description=long_description,
            sources=sources,
            expected_active_version=expected_active_version,
            request_options=request_options,
        )
        return _response.data
